import type { LegalDoc, LegalSlug } from "./legal";

/*
  Albanian courtesy translation of legal documents.
  Italian version is binding — see notice on each document.
  {{tokens}} unchanged (replaced at render-time).
*/

const LANG_NOTE =
  "Versioni italian i këtij dokumenti është ligjërisht detyrues: çdo përkthim është vetëm për lehtësi dhe, në rast mospërputhjeje, mbizotëron versioni italian.";

const LANG_NOTICE = {
  tone: "info" as const,
  text: LANG_NOTE,
};

export const legalDocsSq: Record<LegalSlug, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "Informacion mbi privatësinë",
    eyebrow: "Dokument ligjor",
    intro: "Si i trajtojmë të dhënat tuaja personale kur konsultoni faqen, kërkoni një preventiv, blini një shërbim ose përdorni zonën tuaj personale, në përputhje me GDPR (Rreg. BE 2016/679).",
    updatedAt: "Përditësimi i fundit: 14 korrik 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "p", text: "Në bazë të neneve 13 dhe 14 të Rregullores (BE) 2016/679 (\"GDPR\") dhe D.Lgs. 196/2003 (\"Kodi i Privatësisë\") siç është ndryshuar nga D.Lgs. 101/2018, Studio-ja jep informacionet e mëposhtme mbi trajtimin e të dhënave personale." },
      { type: "h2", text: "1. Titolari i trajtimit" },
      {
        type: "ul",
        items: [
          "Titolari: {{ragione_sociale}} ({{forma_giuridica}})",
          "Selia operative: {{indirizzo}}",
          "P.IVA: {{piva}} - Codice Fiscale: {{cf}}",
          "Regjistrimi në Albo: {{albo}}",
          "PEC: {{pec}} - Email: {{email}} - Telefono: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Përgjegjësi i mbrojtjes së të dhënave (DPO)" },
      { type: "p", text: "Emërimi i një DPO nuk rezulton i detyrueshëm për aktivitetin e ushtruar; vlerësimi dokumentohet nga Titulari dhe përditësohet sipas volumit dhe natyrës së trajtimeve. Për çdo kërkesë në lidhje me të dhënat personale mund të kontaktoni Titularin te kontaktet e seksionit 1." },
      { type: "h2", text: "3. Kategoritë e të dhënave të trajtuara" },
      { type: "p", text: "Sipas ndërveprimit, Titulari mund të trajtojë kategoritë e mëposhtme të të dhënave:" },
      {
        type: "ul",
        items: [
          "Të dhëna identifikuese dhe kontakti: emër, mbiemër, email, numër telefoni.",
          "Të dhëna në lidhje me shërbimin (praktikë trashëgimi): kod fiskal, të dhëna personale dhe patrimoniale të trashëgimtarit dhe të vdekurit, të dhëna mbi pasuri të paluajtshme, llogari bankare dhe marrëdhënie financiare, shkallë afiniteti.",
          "Dokumente: dokument identiteti, certifikatë/akt vdekjeje, vërtetime, certifikime dhe dokumente të tjera të nevojshme për praktikën.",
          "Të dhëna pagese: menaxhohen drejtpërdrejt nga ofruesi i pagesës (Stripe); Titulari nuk ruan të dhënat e plota të kartës.",
          "Të dhëna teknike dhe navigimi: adresë IP, identifikues pajisjesh, log, cookies dhe teknologji të ngjashme (shih seksionin 11 dhe Cookie Policy).",
        ],
      },
      { type: "p", text: "Disa të dhëna mund të lidhen me subjekte të ndryshme nga përdoruesi që i jep (p.sh. trashëgimtarë të tjerë ose i vdekuri): ai që i jep garanton se është i autorizuar t'i komunikojë dhe angazhohet t'i informojë të interesuarit për këtë informacion (neni 14 GDPR)." },
      { type: "h2", text: "4. Qëllimet e trajtimit dhe bazat ligjore" },
      {
        type: "table",
        headers: ["Qëllimi", "Baza ligjore (GDPR)"],
        rows: [
          ["Përgjigje ndaj kërkesave preventivi/kontakti dhe aktivitete parakontraktuale", "Neni 6.1.b (masa parakontraktuale)"],
          ["Ekzekutimi i shërbimit profesional (përgatitja dhe dërgimi telematik i deklaratës së trashëgimisë, voltura)", "Neni 6.1.b (kontratë)"],
          ["Përmbushje detyrimesh fiskale, kontabël dhe ruajtjeje (faturim, mandat profesional)", "Neni 6.1.c (detyrim ligjor)"],
          ["Menaxhimi i pagesave", "Neni 6.1.b dhe 6.1.c"],
          ["Siguria e faqes, parandalimi i abuzimeve/mashtrimeve, integriteti i sistemeve", "Neni 6.1.f (interes legjitim)"],
          ["Marketing direkt / newsletter (nëse aktivizohet)", "Neni 6.1.a (pëlqim)"],
          ["Cookies dhe teknologji jo teknike/profilimi", "Neni 6.1.a (pëlqim)"],
        ],
      },
      { type: "p", text: "Në rregull, nuk parashikohet mbledhja e kategorive të veçanta të të dhënave sipas nenit 9 GDPR. Nëse klienti transmeton spontanisht të dhëna të tepërta (p.sh. informacione shëndetësore në një dokument), Titulari i trajton brenda kufijve të nenit 9.2 dhe rekomandon minimizimin e tyre." },
      { type: "h2", text: "5. Natyra e dhënies" },
      { type: "p", text: "Dorëzimi i të dhënave për qëllime kontraktuale, fiskale dhe ligjore është i nevojshëm: mungesa e tyre e pengon ofrimin e shërbimit. Dorëzimi për qëllime marketingu është fakultativ dhe refuzimi eventual nuk dëmton aksesin në shërbim." },
      { type: "h2", text: "6. Mënyra e trajtimit dhe siguria" },
      { type: "p", text: "Të dhënat trajtohen me mjete informatike dhe masa teknike e organizative të përshtatshme (neni 32 GDPR): enkriptim në transit dhe në pushim, kontroll aksesi, segmentim me Row Level Security, parimi i minimizimit, regjistrim i akseseve (audit log). Aksesi është i rezervuar për Titularin dhe përgjegjësit e autorizuar." },
      { type: "h2", text: "7. Marrësit dhe përgjegjësit e trajtimit" },
      { type: "p", text: "Për të ofruar shërbimin, Titulari mbështetet te ofrues që trajtojnë të dhënat si përgjegjës trajtimi (neni 28 GDPR), të lidhur me marrëveshje të posaçme (DPA). Kategoritë kryesore dhe ofruesit janë:" },
      {
        type: "table",
        headers: ["Ofrues", "Roli / shërbimi", "Vendndodhja e të dhënave"],
        rows: [
          ["Supabase", "Database, autentifikim, ruajtje dokumentesh", "BE"],
          ["Vercel", "Hosting dhe shpërndarje e aplikacionit", "BE (funksione) / e mundshme jashtë BE"],
          ["Stripe", "Përpunim pagesash", "BE/SHBA (SCC)"],
          ["Resend", "Dërgim email transaksional", "BE/SHBA (SCC)"],
          ["Google Workspace", "Email profesional i Studio-s", "BE/SHBA (SCC / DPF)"],
          ["OpenAI", "Nxjerrje e asistuar e të dhënave nga dokumentet e praktikës (mbështetje e brendshme për profesionistin)", "BE/SHBA (SCC / DPF)"],
          ["Meta Platforms (WhatsApp Cloud API)", "Mesazhe (nëse aktivizohet)", "BE/SHBA (SCC)"],
          ["Google (Analytics/Ads)", "Statistika dhe reklama (vetëm me pëlqim paraprak)", "BE/SHBA (SCC)"],
          ["Cloudflare (Turnstile)", "Mbrojtje anti-abuzim e formularëve (nëse aktivizohet)", "BE/SHBA (SCC)"],
        ],
      },
      { type: "p", text: "Të dhënat mund të komunikohen gjithashtu me subjekte publike (p.sh. Agenzia delle Entrate, Katastër) për përmbushjen e shërbimit, me profesionistë të besuar (p.sh. kontabilist/noter) kur nevojitet, dhe me autoritet gjyqësor/forcat e rendit nëse kërkohet me ligj. Të dhënat NUK shpërndahen as nuk u cedohen palëve të treta për qëllime të tyre autonome." },
      { type: "h2", text: "8. Transferimi i të dhënave jashtë BE" },
      { type: "p", text: "Titulari privilegjon ofrues me të dhëna në Bashkimin Evropian. Kur disa ofrues trajtojnë të dhëna jashtë BE (p.sh. në SHBA), transferimi bëhet mbi bazën e garancive të përshtatshme sipas neneve 44 e vij. GDPR, veçanërisht Klauzolat Kontraktuale Standarde (SCC) të Komisionit Evropian dhe/ose vendime adekuacioni (p.sh. EU-US Data Privacy Framework, ku zbatohet)." },
      { type: "h2", text: "9. Periudha e ruajtjes" },
      {
        type: "ul",
        items: [
          "Dokumente fiskale dhe kontabël (fatura, fletëpagesa, mandat, deklaratë): ruhen për afatin ligjor, të paktën 10 vjet (neni 2220 c.c. dhe detyrime fiskale).",
          "Dokumente hyrëse sensitive të ngarkuara nga klienti (p.sh. kartë identiteti): ruhen për kohën e nevojshme për punimin dhe pastaj fshihen nga cloud (minimizim).",
          "Dokumente përfundimtare (fletëpagesa AdE, vërtetime të përditësuara, faturë): vihen në dispozicion në zonën personale të klientit për konsultim; arkivi i plotë ruhet në mënyrë të sigurt.",
          "Të dhëna kontakti për preventivë të pakthyer: fshihen ose anonimizohen brenda 12 muajsh nga kontakti i fundit.",
          "Të dhëna për marketing: deri në revokimin e pëlqimit.",
          "Të dhëna teknike/log dhe cookies: sipas kohëzgjatjeve të treguara në Cookie Policy.",
        ],
      },
      { type: "h2", text: "10. Të drejtat e të interesuarit" },
      { type: "p", text: "Mund të ushtroni në çdo kohë të drejtat e parashikuara nga nenet 15-22 GDPR: akses, korrigjim, fshirje (\"e drejta e harresës\", brenda kufijve të detyrimeve ligjore të ruajtjes), kufizim, portabilitet, kundërshtim ndaj trajtimit të bazuar në interes legjitim, revokim i pëlqimit në çdo kohë (pa dëmtuar ligjshmërinë e trajtimit të mëparshëm)." },
      { type: "p", text: "Kërkesat dërgohen te kontaktet e seksionit 1. Titulari përgjigjet pa vonesë të arsyeshme dhe gjithsesi brenda një muaji. Keni gjithashtu të drejtë të paraqisni ankesë te Garante për mbrojtjen e të dhënave personale (www.garanteprivacy.it)." },
      { type: "h2", text: "11. Cookies dhe teknologji gjurmimi" },
      { type: "p", text: "Faqja përdor cookies teknike dhe, me pëlqim paraprak, cookies statistikore (Google Analytics 4 me Consent Mode: asnjë cookie matjeje nuk vendoset pa pëlqim). Detaji i kategorive, qëllimeve dhe kohëzgjatjeve raportohet në Cookie Policy të dedikuar, e arritshme nga banneri dhe footer-i. Pëlqimi revokohet në çdo kohë nga lidhja \"Preferencat cookies\" në footer." },
      { type: "h2", text: "12. Proces vendimtar i automatizuar dhe inteligjencë artificiale" },
      { type: "p", text: "Nuk kryhet asnjë proces vendimtar i automatizuar që prodhon efekte juridike për të interesuarin sipas nenit 22 GDPR. Studio-ja përdor mjete inteligjence artificiale vetëm si mbështetje e brendshme për aktivitetin e profesionistit: veçanërisht, dokumentet e ngarkuara për praktikën mund të përpunohen përmes shërbimit API të OpenAI (përgjegjës trajtimi, shih seksionin 7) për të nxjerrë të dhënat e nevojshme për përgatitjen e deklaratës (p.sh. të dhëna personale, kadastrale)." },
      {
        type: "ul",
        items: [
          "Të dhënat e dërguara përmes API nuk përdoren nga OpenAI për të trajnuar modelet e veta.",
          "Çdo të dhënë e nxjerrë verifikohet dhe vërtetohet nga profesionisti para përdorimit: vendimi përfundimtar i lihet gjithmonë një personi.",
          "Transferimi jashtë BE eventualisht i lidhur bëhet me garancitë e seksionit 8.",
        ],
      },
      { type: "h2", text: "13. Të mitur" },
      { type: "p", text: "Shërbimet u drejtohen personave të rritur. Titulari nuk mbledh me vetëdije të dhëna të të miturve pa pëlqimin e atij që ushtron përgjegjësinë prindërore." },
      { type: "h2", text: "14. Ndryshime në informacionin" },
      { type: "p", text: "Titulari mund të përditësojë këtë informacion. Versioni në fuqi publikohet gjithmonë në këtë faqe me datën e përditësimit të fundit; në rast ndryshimesh thelbësore do t'u jepet vëmendje e përshtatshme." },
    ],
  },
  termini: {
    slug: "termini",
    title: "Kushtet e shitjes",
    eyebrow: "Dokument ligjor",
    intro: "Kushtet që rregullojnë shitjen në distancë të shërbimeve tona profesionale për konsumatorët (D.Lgs. 206/2005, Kodi i Konsumit).",
    updatedAt: "Përditësimi i fundit: 14 korrik 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "1. Informacione mbi profesionistin (neni 49 Kodi i Konsumit)" },
      {
        type: "ul",
        items: [
          "Profesionist: {{ragione_sociale}} ({{forma_giuridica}})",
          "Selia operative: {{indirizzo}}",
          "P.IVA: {{piva}} - Codice Fiscale: {{cf}}",
          "Regjistrimi në Albo: {{albo}}",
          "PEC: {{pec}} - Email: {{email}} - Telefono: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Objekti dhe fusha e zbatimit" },
      { type: "p", text: "Këto Kushte rregullojnë shitjen në distancë të shërbimeve profesionale të ofruara përmes faqes, që konsistojnë në asistencë për përgatitjen dhe transmetimin telematik të deklaratës së trashëgimisë dhe detyrimeve të lidhura (p.sh. voltura kadastrale), sipas paketës së blerë." },
      { type: "p", text: "Dërgimi telematik te Agenzia delle Entrate bëhet nga profesionisti si ndërmjetës i autorizuar ENTRATEL, pas dhënies së mandatit/porosisë së duhur dhe marrjes së deklaratës së nënshkruar nga klienti. Kontrata lidhet në distancë, në mënyrë elektronike." },
      { type: "h2", text: "3. Paketa, çmime dhe përjashtime" },
      { type: "p", text: "Paketat dhe çmimet përkatëse (honorari) tregohen në faqen Tarifat. Çmimi i treguar i referohet vetëm honorarit profesional." },
      { type: "callout", tone: "warning", title: "Honorari dhe taksat janë gjëra të ndryshme", text: "Taksat dhe tarifat e duhura shtetit (p.sh. taksa e trashëgimisë në autolikuidim, taksat hipotekore, kadastrale, pullë, tarifa speciale) NUK përfshihen në çmimin e shërbimit: llogariten sipas situatës specifike, komunikohen klientit para dërgimit dhe paguhen nga trashëgimtari. Profesionisti nuk aplikon asnjë rritje mbi këto shuma." },
      {
        type: "ul",
        items: [
          "Përjashtohen nga paketa, përveç marrëveshjes së ndryshme, shërbimet që nuk janë shprehur (p.sh. kontencioz, praktika noteriale, këshillime fiskale komplekse, raste jo lineare). Aktivitetet shtesë parashikohen veç e veç.",
          "Preventiv i personalizuar (raste komplekse): për praktikat që për natyrë ose kompleksitet tejkalojnë paketat standarde (p.sh. shumë pasuri të paluajtshme, toka/parcele bujqësore, kuota shoqërore, trashëgimi me testamente, trashëgimtarë jashtë vendit, rikuperim dokumentesh), çmimi përcaktohet me preventiv individual të komunikuar para blerjes.",
          "Paketa e propozuar pas pyetësorit online është orientuese: pas verifikimit të dokumentacionit mund të aplikohet procedura e modifikimit dhe barazimit (neni 5).",
          "Verifikim paraprak i mungesës së detyrimit: kur nga të dhënat e dhëna del se deklarata nuk është e detyrueshme me ligj, profesionisti e sinjalizon klientit; vlerësimi përfundimtar kërkon shqyrtimin e rastit konkret.",
        ],
      },
      { type: "h2", text: "4. Përfundimi i kontratës" },
      { type: "p", text: "Kërkesa e preventivit nuk është detyruese. Kontrata përsoshet me pagesën e paketës dhe pranimin e qartë të këtyre Kushteve në checkout. Para blerjes klienti njeh karakteristikat e shërbimit, çmimin total, këto Kushte dhe informacionin e privatësisë." },
      { type: "h2", text: "5. Pagesa dhe modifikimi i paketës" },
      { type: "p", text: "Pagesa e honorarit bëhet paraprakisht përmes ofruesit të pagesës (Stripe). Fatura lëshohet sipas detyrimeve në fuqi. Taksat shtetërore menaxhohen veç e veç dhe paguhen nga trashëgimtari sipas modaliteteve të komunikuara." },
      { type: "p", text: "Modifikimi i paketës dhe barazimi: kur, me marrëveshje me klientin, paketa modifikohet, bëhet barazimi i diferencës. Në rast kalimi në paketë superiore, klienti plotëson diferencën me lidhje pagese; në rast pakete inferiore, diferenca e paguar kthehet me të njëjtin mjet, pa vonesë. Modifikimi konfirmohet në mbështetje të qëndrueshme. Taksat shtetërore mbeten gjithsesi jashtë barazimit." },
      { type: "h2", text: "6. Detyrimet dhe përgjegjësia e klientit" },
      {
        type: "ul",
        items: [
          "Klienti jep të dhëna dhe dokumente të vërteta, të plota dhe në kohë dhe është përgjegjës për saktësinë e tyre.",
          "Profesionisti nuk përgjigjet për vonesa, gabime ose gjoba që vijnë nga informacione ose dokumente të gabuara, të paplota ose të dorëzuara me vonesë nga klienti, as për kohët e punimit të enteve të treta (Agenzia delle Entrate, Katastër, banka).",
          "Klienti angazhohet të japë mandatin dhe të nënshkruajë deklaratën brenda afateve të kërkuara.",
        ],
      },
      { type: "h2", text: "7. Kohët e ekzekutimit" },
      { type: "p", text: "Kohët e dorëzimit të treguara në faqe janë vlerësime që fillojnë nga momenti kur klienti ka dhënë të gjithë dokumentacionin e nevojshëm, të plotë, të saktë dhe të vërtetuar nga profesionisti (jo nga data e pagesës), dhe nuk përfshijnë kohët e enteve të treta. Derisa dokumentacioni është i paplotë ose në pritje të plotësimit, afati mbetet i pezulluar dhe rifillon nga marrja/vërtetimi i dokumentit të fundit që mungon." },
      { type: "h2", text: "8. E drejta e tërheqjes (nenet 52-59 Kodi i Konsumit)" },
      {
        type: "ul",
        items: [
          "Konsumatori ka të drejtë të tërhiqet nga kontrata brenda 14 ditëve pa dhënë arsye; për shërbimet afati fillon nga përfundimi i kontratës.",
          "Për të ushtruar tërheqjen klienti mund të përdorë modulin tip ose çdo deklaratë të qartë të dërguar te kontaktet e seksionit 1. Profesionisti konfirmon pa vonesë marrjen.",
          "Nisje e menjëhershme: nëse klienti kërkon shprehimisht që punimi të fillojë gjatë periudhës së tërheqjes, jep pëlqim të shprehur për nisjen e menjëhershme dhe pranon se humb të drejtën e tërheqjes kur shërbimi është plotësisht i kryer (neni 59, par. 1, letra a).",
          "Tërheqje pas nisjes por para përfundimit: klienti paguan një shumë proporcionale për shërbimin e dhënë deri në komunikimin e tërheqjes (neni 57, par. 3).",
          "Rimbursimi eventual bëhet me të njëjtin mjet pagese, pa vonesë dhe gjithsesi brenda 14 ditëve.",
        ],
      },
      { type: "callout", tone: "info", text: "E shpjegojmë tërheqjen me fjalë të thjeshta në faqen e dedikuar /recesso. Ky tekst formal është ai që bën fede." },
      { type: "h2", text: "9. Garanci tregtare \"Të kënaqur ose të rimbursuar\"" },
      { type: "p", text: "Profesionisti mund të ofrojë, shtesë dhe vullnetarisht, një garanci rimbursimi sipas kushteve të treguara në faqen Garanci. Kjo garanci është shtesë dhe nuk kufizon të drejtat ligjore të konsumatorit." },
      { type: "h2", text: "10. Kufizime përgjegjësie" },
      { type: "p", text: "Profesionisti e kryen porosinë me kujdes profesional (detyrim mjetesh). Përveç mashtrimit ose fajit të rëndë, dhe brenda kufijve ligjorë, përgjegjësia matet me shumën e honorarit të paguar për praktikën. Profesionisti nuk përgjigjet për ngjarje të imputueshme palëve të treta, forcë madhore ose mungesa funksionimi të ofruesve të jashtëm." },
      { type: "h2", text: "11. Pronësia e dokumenteve dhe aksesi" },
      { type: "p", text: "Dokumentet përfundimtare (fletëpagesa, vërtetime të përditësuara, faturë) vihen në dispozicion në zonën personale të klientit për konsultim dhe shkarkim, sipas kohëve të treguara. Ruajtja rregullohet nga informacioni i privatësisë." },
      { type: "h2", text: "12. Trajtimi i të dhënave personale" },
      { type: "p", text: "Trajtimi i të dhënave përshkruhet në Informacionin e Privatësisë të disponueshëm në faqe, që përbën pjesë integruese të marrëdhënies." },
      { type: "h2", text: "13. Ndryshime" },
      { type: "p", text: "Profesionisti mund të modifikojë këto Kushte; marrëdhënies i aplikohet versioni i pranuar në momentin e blerjes. Versioni në fuqi publikohet gjithmonë në faqe." },
      { type: "h2", text: "14. Ligji i zbatueshëm, fori dhe zgjidhja e mosmarrëveshjeve" },
      { type: "p", text: "Kontratës i aplikohet ligji italian. Për konsumatorët mbetet i patjetërsueshëm fori i vendbanimit/vendqendrës së konsumatorit. Ankesat te kontaktet e seksionit 1. Konsumatori mund të drejtohet te platforma evropiane ODR (https://ec.europa.eu/consumers/odr) dhe te organet e mediacionit/ADR kompetente." },
    ],
  },
  cookie: {
    slug: "cookie",
    title: "Cookie Policy",
    eyebrow: "Dokument ligjor",
    intro: "Cookies dhe teknologjitë e ngjashme që përdorim, dhe si të menaxhoni pëlqimet tuaja.",
    updatedAt: "Përditësimi i fundit: 14 korrik 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Çfarë janë cookies" },
      { type: "p", text: "Cookies janë skedarë të vegjël teksti që faqet i ruajnë në pajisjen tuaj për ta bërë të funksionojë, për të mbajtur mend preferencat tuaja ose për të mbledhur statistika. Së bashku me cookies përdorim teknologji të ngjashme (p.sh. local storage, pixel)." },
      { type: "h2", text: "Kategoritë që përdorim" },
      {
        type: "table",
        headers: ["Kategoria", "Për çfarë shërbejnë", "Baza / pëlqim"],
        rows: [
          ["Teknike / të nevojshme", "Funksionimi i faqes, siguria, sesioni i aksesit në zonën personale, ruajtja e zgjedhjeve mbi cookies.", "Gjithmonë aktive (nuk kërkojnë pëlqim)"],
          ["Analitike (Google Analytics 4)", "Statistika të agreguara mbi përdorimin e faqes për ta përmirësuar. Falë Consent Mode, asnjë cookie matjeje nuk vendoset pa pëlqimin tuaj.", "Vetëm me pëlqim paraprak"],
          ["Marketing", "Matja e fushatave reklamuese dhe atribuimi (p.sh. Google Ads). Aktualisht jo aktive: nëse aktivizohen, do të kërkojnë pëlqim nga banneri.", "Vetëm me pëlqim paraprak"],
        ],
      },
      { type: "h2", text: "Si menaxhoni pëlqimin" },
      { type: "p", text: "Në aksesin e parë një banner ju lejon të pranoni ose refuzoni cookies jo të nevojshme, me të njëjtën dukshmëri midis zgjedhjeve. Mund të modifikoni ose revokoni pëlqimin në çdo kohë nga lidhja \"Preferencat cookies\" në footer të faqes; revokimi nuk dëmton ligjshmërinë e trajtimeve të mëparshme." },
      { type: "h2", text: "Çaktivizim nga shfletuesi" },
      { type: "p", text: "Mund të menaxhoni ose fshini cookies edhe nga cilësimet e shfletuesit tuaj. Çaktivizimi i cookies teknike mund të komprometojë disa funksione të faqes (p.sh. aksesi në zonën personale)." },
      { type: "h2", text: "Titolari dhe kontakte" },
      { type: "p", text: "Titolari i trajtimit: {{ragione_sociale}}, {{indirizzo}}. Email: {{email}} - PEC: {{pec}}. Për detajin mbi trajtimin e të dhënave personale shih Informacionin e privatësisë." },
    ],
  },
  garanzia: {
    slug: "garanzia",
    title: "Garancia jonë",
    eyebrow: "Mbrojtjet tuaja",
    intro: "Premtimi Të kënaqur ose të rimbursuar: një mbrojtje shtesë që ofrojmë ne, përveç të drejtave tuaja ligjore.",
    updatedAt: "Version paraprak - kushte të hollësishme për t'u përcaktuar",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Premtimi" },
      { type: "p", text: "Duam që të jeni të qetë nga fillimi deri në fund. Prandaj, përveç mbrojtjeve ligjore, ofrojmë vullnetarisht një garanci \"Të kënaqur ose të rimbursuar\": nëse diçka nuk shkon si kemi rënë dakord, e diskutojmë dhe gjejmë një zgjidhje, deri te rimbursimi në rastet e parashikuara." },
      { type: "h2", text: "Si funksionon" },
      {
        type: "ol",
        items: [
          "Na sinjalizoni problemin duke na shkruar ose nga zona juaj personale.",
          "Verifikojmë së bashku situatën, në mënyrë transparente.",
          "Nëse bie brenda rasteve të mbuluara, procedojmë me rimbursim me të njëjtin metodë pagese, brenda kohëve të treguara. (Rastet, shumat dhe kohët specifike: për t'u përcaktuar.)",
        ],
      },
      { type: "callout", tone: "info", title: "Garancia dhe tërheqja janë dy gjëra të ndryshme", text: "Tërheqja është e drejta juaj ligjore në 14 ditët e para (shih faqen Tërheqje). Garancia Të kënaqur ose të rimbursuar është një premtim tregtar shtesë, vullnetar, që nuk kufizon në asnjë mënyrë të drejtat tuaja si konsumator." },
      { type: "h2", text: "Çfarë nuk mbulon" },
      {
        type: "ul",
        items: [
          "Taksat dhe tarifat e duhura shtetit (nuk janë honorari ynë dhe nuk kanë rritje).",
          "Vonesat ose rezultatet që varen nga dokumente të gabuara, të paplota ose të dorëzuara me vonesë nga klienti.",
          "Kohët dhe vendimet e enteve të treta (Agenzia delle Entrate, Katastër, banka).",
        ],
      },
    ],
    cta: { label: "Llogaritni preventivin falas", href: "/preventivo" },
  },
};
