import type { LegalDoc, LegalSlug } from "./legal";

/*
  French courtesy translation of legal documents.
  Italian version is binding — see notice on each document.
  {{tokens}} unchanged (replaced at render-time).
*/

const LANG_NOTE =
  "La version italienne de ce document fait foi : toute traduction est fournie à titre de courtoisie et, en cas de divergence, la version italienne prévaut.";

const LANG_NOTICE = {
  tone: "info" as const,
  text: LANG_NOTE,
};

export const legalDocsFr: Record<LegalSlug, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "Politique de confidentialité",
    eyebrow: "Document juridique",
    intro: "Comment nous traitons vos données personnelles lorsque vous consultez le site, demandez un devis, achetez un service ou utilisez votre espace personnel, conformément au RGPD (Règl. UE 2016/679).",
    updatedAt: "Dernière mise à jour : 14 juillet 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "p", text: "Conformément aux articles 13 et 14 du Règlement (UE) 2016/679 (« RGPD ») et au D.Lgs. 196/2003 (« Code de la confidentialité ») tel que modifié par le D.Lgs. 101/2018, le Studio fournit les informations suivantes sur le traitement des données personnelles." },
      { type: "h2", text: "1. Responsable du traitement" },
      {
        type: "ul",
        items: [
          "Responsable : {{ragione_sociale}} ({{forma_giuridica}})",
          "Siège opérationnel : {{indirizzo}}",
          "P.IVA : {{piva}} - C.F. : {{cf}}",
          "Inscription au registre : {{albo}}",
          "PEC : {{pec}} - E-mail : {{email}} - Téléphone : {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Délégué à la protection des données (DPO)" },
      { type: "p", text: "La nomination d'un DPO ne semble pas obligatoire pour l'activité exercée ; l'évaluation est documentée par le Responsable et mise à jour en fonction des volumes et de la nature des traitements. Pour toute demande relative aux données personnelles, vous pouvez contacter le Responsable aux coordonnées de la section 1." },
      { type: "h2", text: "3. Catégories de données traitées" },
      { type: "p", text: "Selon l'interaction, le Responsable peut traiter les catégories de données suivantes :" },
      {
        type: "ul",
        items: [
          "Données d'identification et de contact : nom, prénom, e-mail, numéro de téléphone.",
          "Données relatives au service (dossier de succession) : code fiscal, données personnelles et patrimoniales de l'héritier et du défunt, données sur les immeubles, comptes courants et relations financières, degrés de parenté.",
          "Documents : pièce d'identité, certificat/acte de décès, visures, attestations et autres documents nécessaires au dossier.",
          "Données de paiement : gérées directement par le prestataire de paiement (Stripe) ; le Responsable ne stocke pas les données complètes de la carte.",
          "Données techniques et de navigation : adresse IP, identifiants des appareils, journaux, cookies et technologies similaires (voir section 11 et Politique cookies).",
        ],
      },
      { type: "p", text: "Certaines données peuvent concerner des personnes autres que l'utilisateur qui les communique (p. ex. d'autres héritiers ou le défunt) : celui qui les fournit garantit être habilité à les communiquer et s'engage à informer les personnes concernées de la présente notice (art. 14 RGPD)." },
      { type: "h2", text: "4. Finalités du traitement et bases juridiques" },
      {
        type: "table",
        headers: ["Finalité", "Base juridique (RGPD)"],
        rows: [
          ["Réponse aux demandes de devis/contact et activités précontractuelles", "Art. 6.1.b (mesures précontractuelles)"],
          ["Exécution du service professionnel (préparation et envoi télématique de la déclaration de succession, voluture)", "Art. 6.1.b (contrat)"],
          ["Obligations fiscales, comptables et de conservation (facturation, mandat professionnel)", "Art. 6.1.c (obligation légale)"],
          ["Gestion des paiements", "Art. 6.1.b et 6.1.c"],
          ["Sécurité du site, prévention des abus/fraudes, intégrité des systèmes", "Art. 6.1.f (intérêt légitime)"],
          ["Marketing direct / newsletter (si activé)", "Art. 6.1.a (consentement)"],
          ["Cookies et technologies non techniques/de profilage", "Art. 6.1.a (consentement)"],
        ],
      },
      { type: "p", text: "En principe, la collecte de catégories particulières de données au sens de l'art. 9 RGPD n'est pas prévue. Si le client transmet spontanément des données excédentaires (p. ex. informations sanitaires dans un document), le Responsable les traite dans les limites de l'art. 9.2 et recommande leur minimisation." },
      { type: "h2", text: "5. Nature de la communication" },
      { type: "p", text: "La communication des données pour les finalités contractuelles, fiscales et légales est nécessaire : en cas de refus, le service ne peut pas être fourni. La communication pour des finalités de marketing est facultative et un éventuel refus n'affecte pas l'accès au service." },
      { type: "h2", text: "6. Modalités du traitement et sécurité" },
      { type: "p", text: "Les données sont traitées avec des outils informatiques et des mesures techniques et organisationnelles adéquates (art. 32 RGPD) : chiffrement en transit et au repos, contrôle des accès, segmentation par Row Level Security, principe de minimisation, enregistrement des accès (journal d'audit). L'accès est réservé au Responsable et aux sous-traitants autorisés." },
      { type: "h2", text: "7. Destinataires et sous-traitants" },
      { type: "p", text: "Pour fournir le service, le Responsable s'appuie sur des prestataires qui traitent les données en qualité de sous-traitants (art. 28 RGPD), liés par un accord approprié (DPA). Les principales catégories et prestataires sont :" },
      {
        type: "table",
        headers: ["Prestataire", "Rôle / service", "Localisation des données"],
        rows: [
          ["Supabase", "Base de données, authentification, stockage de documents", "UE"],
          ["Vercel", "Hébergement et distribution de l'application", "UE (fonctions) / éventuellement hors UE"],
          ["Stripe", "Traitement des paiements", "UE/USA (SCC)"],
          ["Resend", "Envoi d'e-mails transactionnels", "UE/USA (SCC)"],
          ["Google Workspace", "E-mail professionnelle du Studio", "UE/USA (SCC / DPF)"],
          ["OpenAI", "Extraction assistée des données des documents du dossier (soutien interne au professionnel)", "UE/USA (SCC / DPF)"],
          ["Meta Platforms (WhatsApp Cloud API)", "Messagerie (si activée)", "UE/USA (SCC)"],
          ["Google (Analytics/Ads)", "Statistiques et publicité (uniquement avec consentement préalable)", "UE/USA (SCC)"],
          ["Cloudflare (Turnstile)", "Protection anti-abus des formulaires (si activée)", "UE/USA (SCC)"],
        ],
      },
      { type: "p", text: "Les données peuvent en outre être communiquées à des organismes publics (p. ex. Agenzia delle Entrate, Cadastre) pour l'exécution du service, à des professionnels de confiance (p. ex. expert-comptable/notaire) si nécessaire, et aux autorités judiciaires/forces de l'ordre si la loi l'exige. Les données ne sont NI diffusées NI cédées à des tiers pour leurs propres finalités." },
      { type: "h2", text: "8. Transfert des données hors UE" },
      { type: "p", text: "Le Responsable privilégie les prestataires dont les données se trouvent dans l'Union européenne. Lorsque certains prestataires traitent des données en dehors de l'UE (p. ex. aux USA), le transfert s'effectue sur la base de garanties adéquates au sens des art. 44 et s. RGPD, notamment les Clauses Contractuelles Types (SCC) de la Commission européenne et/ou les décisions d'adéquation (p. ex. EU-US Data Privacy Framework, le cas échéant)." },
      { type: "h2", text: "9. Durée de conservation" },
      {
        type: "ul",
        items: [
          "Documents fiscaux et comptables (factures, reçus, mandat, déclaration) : conservés pendant la durée légale, au moins 10 ans (art. 2220 c.c. et obligations fiscales).",
          "Documents sensibles téléchargés par le client (p. ex. carte d'identité) : conservés le temps nécessaire au traitement puis supprimés du cloud (minimisation).",
          "Documents finaux (reçus AdE, visures mises à jour, facture) : mis à disposition dans l'espace personnel du client pour consultation ; l'archive complète est conservée en sécurité.",
          "Données de contact pour les devis non convertis : supprimées ou anonymisées dans les 12 mois suivant le dernier contact.",
          "Données marketing : jusqu'à révocation du consentement.",
          "Données techniques/journaux et cookies : selon les durées indiquées dans la Politique cookies.",
        ],
      },
      { type: "h2", text: "10. Droits de la personne concernée" },
      { type: "p", text: "Vous pouvez exercer à tout moment les droits prévus aux art. 15-22 RGPD : accès, rectification, effacement (« droit à l'oubli », dans les limites des obligations légales de conservation), limitation, portabilité, opposition au traitement fondé sur l'intérêt légitime, révocation du consentement à tout moment (sans affecter la licéité du traitement antérieur)." },
      { type: "p", text: "Les demandes doivent être envoyées aux coordonnées de la section 1. Le Responsable répond sans retard injustifié et en tout cas dans un délai d'un mois. Vous avez également le droit de déposer une réclamation auprès du Garante per la protezione dei dati personali (www.garanteprivacy.it)." },
      { type: "h2", text: "11. Cookies et technologies de suivi" },
      { type: "p", text: "Le site utilise des cookies techniques et, avec consentement préalable, des cookies statistiques (Google Analytics 4 avec Consent Mode : aucun cookie de mesure n'est posé sans consentement). Le détail des catégories, finalités et durées figure dans la Politique cookies dédiée, accessible depuis la bannière et le pied de page. Le consentement est révocable à tout moment via le lien « Préférences cookies » dans le pied de page." },
      { type: "h2", text: "12. Processus décisionnel automatisé et intelligence artificielle" },
      { type: "p", text: "Aucun processus décisionnel automatisé produisant des effets juridiques sur la personne concernée au sens de l'art. 22 RGPD n'est effectué. Le Studio utilise des outils d'intelligence artificielle exclusivement comme soutien interne à l'activité du professionnel : en particulier, les documents téléchargés pour le dossier peuvent être traités via le service API d'OpenAI (sous-traitant, voir section 7) pour en extraire les données nécessaires à la préparation de la déclaration (p. ex. données personnelles, cadastrales)." },
      {
        type: "ul",
        items: [
          "Les données envoyées via API ne sont pas utilisées par OpenAI pour entraîner ses propres modèles.",
          "Chaque donnée extraite est vérifiée et validée par le professionnel avant utilisation : la décision finale est toujours laissée à une personne.",
          "Le transfert hors UE éventuellement lié s'effectue avec les garanties de la section 8.",
        ],
      },
      { type: "h2", text: "13. Mineurs" },
      { type: "p", text: "Les services s'adressent à des personnes majeures. Le Responsable ne collecte pas sciemment de données de mineurs sans le consentement de celui qui exerce la responsabilité parentale." },
      { type: "h2", text: "14. Modifications de la notice" },
      { type: "p", text: "Le Responsable peut mettre à jour la présente notice. La version en vigueur est toujours publiée sur cette page avec la date de dernière mise à jour ; en cas de modifications substantielles, une mention appropriée sera faite." },
    ],
  },
  termini: {
    slug: "termini",
    title: "Conditions de vente",
    eyebrow: "Document juridique",
    intro: "Les conditions générales régissant la vente à distance de nos services professionnels aux consommateurs (D.Lgs. 206/2005, Code de la consommation).",
    updatedAt: "Dernière mise à jour : 14 juillet 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "1. Informations sur le professionnel (art. 49 Code consommation)" },
      {
        type: "ul",
        items: [
          "Professionnel : {{ragione_sociale}} ({{forma_giuridica}})",
          "Siège opérationnel : {{indirizzo}}",
          "P.IVA : {{piva}} - C.F. : {{cf}}",
          "Inscription au registre : {{albo}}",
          "PEC : {{pec}} - E-mail : {{email}} - Téléphone : {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Objet et champ d'application" },
      { type: "p", text: "Les présentes Conditions régissent la vente à distance des services professionnels proposés via le site, consistant en l'assistance à la préparation et à la transmission télématique de la déclaration de succession et des obligations connexes (p. ex. voluture cadastrale), selon le forfait acheté." },
      { type: "p", text: "L'envoi télématique à l'Agenzia delle Entrate est effectué par le professionnel en qualité d'intermédiaire habilité ENTRATEL, après octroi d'un mandat/encadrement approprié et réception de la déclaration signée par le client. Le contrat se conclut à distance, par voie électronique." },
      { type: "h2", text: "3. Forfaits, prix et exclusions" },
      { type: "p", text: "Les forfaits et les prix correspondants (honoraire) sont indiqués sur la page Tarifs. Le prix indiqué se réfère exclusivement à l'honoraire professionnel." },
      { type: "callout", tone: "warning", title: "Honoraire et impôts sont deux choses distinctes", text: "Les impôts et prélèvements dus à l'État (p. ex. droit de succession en autoliquidation, impôts hypothécaire, cadastral, de timbre, prélèvements spéciaux) ne sont PAS compris dans le prix du service : ils sont calculés selon la situation concrète, communiqués au client avant l'envoi et payés par l'héritier. Le professionnel n'applique aucun supplément sur ces montants." },
      {
        type: "ul",
        items: [
          "Sont exclus du forfait, sauf accord contraire, les services non expressément indiqués (p. ex. contentieux, actes notariés, conseils fiscaux complexes, cas non simples). Les activités supplémentaires font l'objet d'un devis séparé.",
          "Devis personnalisé (cas complexes) : pour les dossiers qui, par nature ou complexité, dépassent les forfaits standard (p. ex. pluralité d'immeubles, terrains/parcelles agricoles, parts sociales, successions testamentaires, héritiers à l'étranger, recherche documentaire), le prix est déterminé par un devis individuel communiqué avant l'achat.",
          "Le forfait proposé à l'issue du questionnaire en ligne est indicatif : après vérification de la documentation, la procédure de modification et de régularisation (art. 5) peut s'appliquer.",
          "Vérification préliminaire de non-obligation : lorsque les données fournies indiquent que la déclaration n'est pas due en droit, le professionnel l'indique au client ; l'évaluation définitive exige l'examen du cas concret.",
        ],
      },
      { type: "h2", text: "4. Conclusion du contrat" },
      { type: "p", text: "La demande de devis n'est pas contraignante. Le contrat se perfectionne avec le paiement du forfait et l'acceptation explicite des présentes Conditions lors du checkout. Avant l'achat, le client prend connaissance des caractéristiques du service, du prix total, des présentes Conditions et de la notice de confidentialité." },
      { type: "h2", text: "5. Paiement et modification du forfait" },
      { type: "p", text: "Le paiement de l'honoraire s'effectue à l'avance via le prestataire de paiement (Stripe). La facture est émise conformément aux obligations en vigueur. Les impôts d'État sont gérés séparément et payés par l'héritier selon les modalités communiquées." },
      { type: "p", text: "Modification du forfait et régularisation : si, d'accord avec le client, le forfait est modifié, la différence est régularisée. En cas de passage à un forfait supérieur, le client complète la différence via un lien de paiement ; en cas de forfait inférieur, la différence déjà versée est remboursée par le même moyen, sans retard. La modification est confirmée sur support durable. Les impôts d'État restent en tout cas exclus de la régularisation." },
      { type: "h2", text: "6. Obligations et responsabilité du client" },
      {
        type: "ul",
        items: [
          "Le client fournit des données et documents véridiques, complets et ponctuels et en est responsable.",
          "Le professionnel n'est pas responsable des retards, erreurs ou sanctions résultant d'informations ou documents erronés, incomplets ou fournis tardivement par le client, ni des délais de traitement des organismes tiers (Agenzia delle Entrate, Cadastre, banques).",
          "Le client s'engage à conférer le mandat et à signer la déclaration dans les délais requis.",
        ],
      },
      { type: "h2", text: "7. Délais d'exécution" },
      { type: "p", text: "Les délais de livraison indiqués sur le site sont des estimations courant à partir du moment où le client a fourni toute la documentation nécessaire, complète, correcte et validée par le professionnel (et non à partir de la date de paiement), et ne comprennent pas les délais des organismes tiers. Tant que la documentation est incomplète ou en attente de complément, le délai reste suspendu et reprend à la réception/validation du dernier document manquant." },
      { type: "h2", text: "8. Droit de rétractation (art. 52-59 Code consommation)" },
      {
        type: "ul",
        items: [
          "Le consommateur a le droit de se rétracter du contrat dans les 14 jours sans avoir à motiver sa décision ; pour les services, le délai court à compter de la conclusion du contrat.",
          "Pour exercer la rétractation, le client peut utiliser le formulaire type ou toute déclaration explicite envoyée aux coordonnées de la section 1. Le professionnel confirme sans retard la réception.",
          "Démarrage immédiat : si le client demande expressément que le traitement commence pendant la période de rétractation, il donne son consentement exprès au démarrage immédiat et reconnaît qu'il perd le droit de rétractation une fois la prestation intégralement exécutée (art. 59, al. 1, let. a).",
          "Rétractation après le démarrage mais avant l'achèvement : le client paie un montant proportionnel au service déjà rendu jusqu'à la communication de la rétractation (art. 57, al. 3).",
          "Le remboursement éventuel est effectué par le même moyen de paiement, sans retard et en tout cas dans les 14 jours.",
        ],
      },
      { type: "callout", tone: "info", text: "Nous expliquons la rétractation en termes simples sur la page dédiée /recesso. Ce texte formel fait foi." },
      { type: "h2", text: "9. Garantie commerciale « Satisfait ou remboursé »" },
      { type: "p", text: "Le professionnel peut offrir, en plus et volontairement, une garantie de remboursement aux conditions indiquées sur la page Garantie. Cette garantie est additionnelle et ne limite pas les droits légaux du consommateur." },
      { type: "h2", text: "10. Limitations de responsabilité" },
      { type: "p", text: "Le professionnel exécute la mission avec la diligence professionnelle (obligation de moyens). Sauf dol ou faute lourde, et dans les limites légales, la responsabilité est proportionnée au montant de l'honoraire versé pour le dossier. Le professionnel n'est pas responsable des événements imputables à des tiers, à la force majeure ou à des dysfonctionnements de prestataires externes." },
      { type: "h2", text: "11. Propriété des documents et accès" },
      { type: "p", text: "Les documents finaux (reçus, visures mises à jour, facture) sont mis à disposition dans l'espace personnel du client pour consultation et téléchargement, selon les délais indiqués. La conservation est régie par la notice de confidentialité." },
      { type: "h2", text: "12. Traitement des données personnelles" },
      { type: "p", text: "Le traitement des données est décrit dans la Notice de confidentialité disponible sur le site, qui fait partie intégrante de la relation." },
      { type: "h2", text: "13. Modifications" },
      { type: "p", text: "Le professionnel peut modifier les présentes Conditions ; le contrat est régi par la version acceptée au moment de l'achat. La version en vigueur est toujours publiée sur le site." },
      { type: "h2", text: "14. Droit applicable, juridiction et règlement des litiges" },
      { type: "p", text: "Le contrat est régi par le droit italien. Pour les consommateurs, le for impératif du lieu de résidence/domicile du consommateur reste applicable. Réclamations aux coordonnées de la section 1. Le consommateur peut recourir à la plateforme européenne ODR (https://ec.europa.eu/consumers/odr) et aux organismes de médiation/ADR compétents." },
    ],
  },
  cookie: {
    slug: "cookie",
    title: "Politique cookies",
    eyebrow: "Document juridique",
    intro: "Les cookies et technologies similaires que nous utilisons, et comment gérer vos consentements.",
    updatedAt: "Dernière mise à jour : 14 juillet 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Que sont les cookies" },
      { type: "p", text: "Les cookies sont de petits fichiers texte que les sites enregistrent sur votre appareil pour le faire fonctionner, mémoriser vos préférences ou recueillir des statistiques. Avec les cookies, nous utilisons des technologies similaires (p. ex. stockage local, pixel)." },
      { type: "h2", text: "Catégories que nous utilisons" },
      {
        type: "table",
        headers: ["Catégorie", "À quoi ils servent", "Base / consentement"],
        rows: [
          ["Techniques / nécessaires", "Fonctionnement du site, sécurité, session d'accès à l'espace personnel, mémorisation des choix relatifs aux cookies.", "Toujours actifs (sans consentement requis)"],
          ["Analytiques (Google Analytics 4)", "Statistiques agrégées sur l'utilisation du site pour l'améliorer. Grâce au Consent Mode, aucun cookie de mesure n'est posé sans votre consentement.", "Uniquement avec consentement préalable"],
          ["Marketing", "Mesure des campagnes publicitaires et attribution (p. ex. Google Ads). Non actifs pour le moment : s'ils sont activés, le consentement sera requis via la bannière.", "Uniquement avec consentement préalable"],
        ],
      },
      { type: "h2", text: "Comment gérer le consentement" },
      { type: "p", text: "Lors de la première visite, une bannière vous permet d'accepter ou de refuser les cookies non nécessaires, avec la même visibilité entre les choix. Vous pouvez modifier ou révoquer le consentement à tout moment via le lien « Préférences cookies » dans le pied de page du site ; la révocation n'affecte pas la licéité des traitements antérieurs." },
      { type: "h2", text: "Désactivation via le navigateur" },
      { type: "p", text: "Vous pouvez aussi gérer ou supprimer les cookies dans les paramètres de votre navigateur. La désactivation des cookies techniques peut compromettre certaines fonctions du site (p. ex. l'accès à l'espace personnel)." },
      { type: "h2", text: "Responsable et contacts" },
      { type: "p", text: "Responsable du traitement : {{ragione_sociale}}, {{indirizzo}}. E-mail : {{email}} - PEC : {{pec}}. Pour le détail du traitement des données personnelles, voir la Notice de confidentialité." },
    ],
  },
  garanzia: {
    slug: "garanzia",
    title: "Notre garantie",
    eyebrow: "Vos garanties",
    intro: "La promesse Satisfait ou remboursé : une protection supplémentaire que nous offrons, au-delà de vos droits légaux.",
    updatedAt: "Version préliminaire - conditions détaillées à définir",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "La promesse" },
      { type: "p", text: "Nous voulons que vous soyez serein du début à la fin. C'est pourquoi, en plus des protections légales, nous offrons volontairement une garantie « Satisfait ou remboursé » : si quelque chose ne se passe pas comme convenu, nous en discutons et trouvons une solution, jusqu'au remboursement dans les cas prévus." },
      { type: "h2", text: "Comment ça marche" },
      {
        type: "ol",
        items: [
          "Vous signalez le problème en nous écrivant ou depuis votre espace personnel.",
          "Nous vérifions ensemble la situation, de manière transparente.",
          "Si cela entre dans les cas couverts, nous procédons au remboursement par le même moyen de paiement, dans les délais indiqués. (Cas, montants et délais spécifiques : à définir.)",
        ],
      },
      { type: "callout", tone: "info", title: "Garantie et rétractation sont deux choses distinctes", text: "La rétractation est votre droit légal dans les 14 premiers jours (voir page Rétractation). La garantie Satisfait ou remboursé est une promesse commerciale supplémentaire, volontaire, qui ne limite en aucun cas vos droits de consommateur." },
      { type: "h2", text: "Ce que cela ne couvre pas" },
      {
        type: "ul",
        items: [
          "Les impôts et prélèvements dus à l'État (ce n'est pas notre honoraire et il n'y a pas de supplément).",
          "Retards ou résultats liés à des documents erronés, incomplets ou fournis tardivement par le client.",
          "Délais et décisions des organismes tiers (Agenzia delle Entrate, Cadastre, banques).",
        ],
      },
    ],
    cta: { label: "Calculez le devis gratuitement", href: "/preventivo" },
  },
};
