import type { LegalDoc, LegalSlug } from "./legal";

/*
  English courtesy translation of legal documents.
  Italian version is binding — see notice on each document.
  {{tokens}} unchanged (replaced at render-time).
*/

const LANG_NOTE =
  "The Italian version of this document is legally binding: any translation is for convenience only and, in case of discrepancy, the Italian version prevails.";

const LANG_NOTICE = {
  tone: "info" as const,
  text: LANG_NOTE,
};

export const legalDocsEn: Record<LegalSlug, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "Privacy notice",
    eyebrow: "Legal document",
    intro: "How we process your personal data when you browse the site, request a quote, purchase a service or use your client area, in accordance with the GDPR (EU Reg. 2016/679).",
    updatedAt: "Last updated: 14 July 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "p", text: "Pursuant to Articles 13 and 14 of Regulation (EU) 2016/679 (\"GDPR\") and Legislative Decree 196/2003 (\"Privacy Code\") as amended by Legislative Decree 101/2018, the Studio provides the following information on personal data processing." },
      { type: "h2", text: "1. Data controller" },
      {
        type: "ul",
        items: [
          "Controller: {{ragione_sociale}} ({{forma_giuridica}})",
          "Operating address: {{indirizzo}}",
          "VAT no. P.IVA: {{piva}} - Tax code C.F.: {{cf}}",
          "Board registration: {{albo}}",
          "PEC: {{pec}} - Email: {{email}} - Phone: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Data Protection Officer (DPO)" },
      { type: "p", text: "Appointing a DPO is not mandatory for the activity carried out; the assessment is documented by the Controller and updated based on volumes and nature of processing. For any personal data request you may contact the Controller using the details in section 1." },
      { type: "h2", text: "3. Categories of data processed" },
      { type: "p", text: "Depending on the interaction, the Controller may process the following categories of data:" },
      {
        type: "ul",
        items: [
          "Identity and contact data: name, surname, email, phone number.",
          "Service-related data (succession case): tax code, identity and estate data of heirs and deceased, properties, accounts and financial relationships, degrees of kinship.",
          "Documents: ID document, death certificate/deed, cadastral searches, certifications and other documents needed for the case.",
          "Payment data: handled directly by the payment provider (Stripe); the Controller does not store full card details.",
          "Technical and browsing data: IP address, device identifiers, logs, cookies and similar technologies (see section 11 and the Cookie Policy).",
        ],
      },
      { type: "p", text: "Some data may concern persons other than the user who provides them (e.g. other heirs or the deceased): the provider warrants they are authorised and undertakes to inform the data subjects of this notice (Article 14 GDPR)." },
      { type: "h2", text: "4. Purposes of processing and legal bases" },
      {
        type: "table",
        headers: ["Purpose", "Legal basis (GDPR)"],
        rows: [
          ["Responding to quote/contact requests and pre-contractual activities", "Art. 6.1.b (pre-contractual measures)"],
          ["Performing the professional service (preparing and electronically filing the succession declaration, cadastral transfers)", "Art. 6.1.b (contract)"],
          ["Tax, accounting and retention obligations (invoicing, professional mandate)", "Art. 6.1.c (legal obligation)"],
          ["Payment management", "Art. 6.1.b and 6.1.c"],
          ["Site security, prevention of abuse/fraud, system integrity", "Art. 6.1.f (legitimate interest)"],
          ["Direct marketing / newsletter (if activated)", "Art. 6.1.a (consent)"],
          ["Cookies and non-technical/profiling technologies", "Art. 6.1.a (consent)"],
        ],
      },
      { type: "p", text: "As a rule, collection of special categories of data under Art. 9 GDPR is not envisaged. Where necessary for the service, processing is based on Art. 9.2.a or other applicable bases." },
      { type: "h2", text: "5. Nature of provision" },
      { type: "p", text: "Providing data for contractual, tax and legal purposes is necessary: without it the service cannot be performed. Marketing or non-essential cookie consent is optional." },
      { type: "h2", text: "6. Processing methods and security" },
      { type: "p", text: "Data are processed with IT tools and appropriate technical and organisational measures (encryption, access control, backups, EU hosting where possible)." },
      { type: "h2", text: "7. Recipients and processors" },
      { type: "p", text: "To deliver the service, the Controller uses providers that process data as processors or independent controllers:" },
      {
        type: "table",
        headers: ["Provider", "Role / service", "Data location"],
        rows: [
          ["Supabase", "Database, authentication, document storage", "EU"],
          ["Vercel", "Application hosting and delivery", "EU (functions) / possible non-EU"],
          ["Stripe", "Payment processing", "EU/USA (SCCs)"],
          ["Resend", "Transactional email delivery", "EU/USA (SCCs)"],
          ["Google Workspace", "Studio professional email", "EU/USA (SCCs / DPF)"],
          ["OpenAI", "Assisted extraction of data from case documents (internal support for the professional)", "EU/USA (SCCs / DPF)"],
          ["Meta Platforms (WhatsApp Cloud API)", "Messaging (if activated)", "EU/USA (SCCs)"],
          ["Google (Analytics/Ads)", "Statistics and advertising (only with prior consent)", "EU/USA (SCCs)"],
          ["Cloudflare (Turnstile)", "Anti-abuse protection for forms (if activated)", "EU/USA (SCCs)"],
        ],
      },
      { type: "p", text: "Data may also be disclosed to public bodies (e.g. Agenzia delle Entrate, Cadastre) as required to perform the service and for legal obligations." },
      { type: "h2", text: "8. Transfers of data outside the EU" },
      { type: "p", text: "The Controller prefers providers with data in the European Union. When some providers process data outside the EU, appropriate safeguards apply (Standard Contractual Clauses, adequacy decisions, Data Privacy Framework where applicable)." },
      { type: "h2", text: "9. Retention period" },
      {
        type: "ul",
        items: [
          "Tax and accounting documents (invoices, receipts, mandate, declaration): retained for the periods required by tax/civil law (normally 10 years).",
          "Sensitive input documents uploaded by the client (e.g. ID card): retained for the time needed for the case and then deleted or anonymised according to the privacy policy.",
          "Final documents (AdE receipts, updated searches, invoice): made available in the client area and retained as needed for the service and legal obligations.",
          "Contact data for quotes not converted: deleted or anonymised within 12 months of the last contact.",
          "Marketing data: until consent is withdrawn.",
          "Technical/log data and cookies: according to the durations in the Cookie Policy.",
        ],
      },
      { type: "h2", text: "10. Data subject rights" },
      { type: "p", text: "You may exercise at any time the rights under Arts. 15–22 GDPR: access, rectification, erasure, restriction, portability, objection, and withdrawal of consent where processing is based on consent." },
      { type: "p", text: "Requests should be sent to the contacts in section 1. The Controller responds without undue delay and in any case within one month." },
      { type: "h2", text: "11. Cookies and tracking technologies" },
      { type: "p", text: "The site uses technical cookies and, with prior consent, analytics cookies (Google Analytics 4 with Consent Mode). Details are in the Cookie Policy." },
      { type: "h2", text: "12. Automated decision-making and artificial intelligence" },
      { type: "p", text: "No automated decision-making that produces legal effects on the user or similarly significantly affects them is carried out." },
      {
        type: "ul",
        items: [
          "Data sent via API are not used by OpenAI to train its models.",
          "Every extracted datum is verified and validated by the professional before use: the decision remains human.",
          "Any related non-EU transfer takes place with the safeguards in section 8.",
        ],
      },
      { type: "h2", text: "13. Minors" },
      { type: "p", text: "Services are aimed at adults. The Controller does not knowingly collect data of minors without the involvement of those with parental responsibility." },
      { type: "h2", text: "14. Changes to this notice" },
      { type: "p", text: "The Controller may update this notice. The current version is always published on the site with the update date." },
    ],
  },
  termini: {
    slug: "termini",
    title: "Terms of sale",
    eyebrow: "Legal document",
    intro: "The terms and conditions governing distance selling of our professional services for succession declarations.",
    updatedAt: "Last updated: 14 July 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "1. Information about the professional (Art. 49 Consumer Code)" },
      {
        type: "ul",
        items: [
          "Professional: {{ragione_sociale}} ({{forma_giuridica}})",
          "Operating address: {{indirizzo}}",
          "VAT no. P.IVA: {{piva}} - Tax code C.F.: {{cf}}",
          "Board registration: {{albo}}",
          "PEC: {{pec}} - Email: {{email}} - Phone: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Subject and scope" },
      { type: "p", text: "These Terms govern distance selling of professional services offered through the site relating to preparation and electronic filing of the succession declaration and related activities included in the packages." },
      { type: "p", text: "Electronic filing with Agenzia delle Entrate is performed by the professional as an authorised Entratel intermediary." },
      { type: "h2", text: "3. Packages, prices and exclusions" },
      { type: "p", text: "Packages and related prices (fee) are shown on the Pricing page. The indicated price is the professional fee without VAT (flat-rate regime)." },
      { type: "callout", tone: "warning", title: "Fee and taxes are different things", text: "Taxes and duties owed to the State (e.g. self-assessed succession tax, mortgage and cadastral taxes, stamps) are not included in the fee: they are calculated on the specific case, notified before filing and paid by the client." },
      {
        type: "ul",
        items: [
          "Unless otherwise agreed, services not expressly listed are excluded from the package (e.g. notarial deeds, disputes, subsequent acts).",
          "Custom quote (complex cases): for cases that by nature or complexity exceed standard packages, a dedicated quote is prepared.",
          "The package proposed after the online questionnaire is indicative: after checking documentation the professional may suggest a change, with settlement of the difference only.",
          "Preliminary check of non-obligation: where the data suggest the declaration is not required, we say so and do not sell a useless service.",
        ],
      },
      { type: "h2", text: "4. Conclusion of the contract" },
      { type: "p", text: "A quote request is not binding. The contract is concluded upon payment of the fee for the chosen package (or acceptance of the custom quote)." },
      { type: "h2", text: "5. Payment and package changes" },
      { type: "p", text: "Payment of the fee is made in advance via the payment provider (Stripe). Instalment options may be available for the fee only, not for taxes." },
      { type: "p", text: "Package change and settlement: if, by agreement with the client, the package is changed after purchase, only the difference is settled." },
      { type: "h2", text: "6. Client obligations and liability" },
      {
        type: "ul",
        items: [
          "The client provides true, complete and timely data and documents and is responsible for their accuracy.",
          "The professional is not liable for delays, errors or penalties arising from incorrect, incomplete or late information or documents from the client.",
          "The client undertakes to grant the mandate and sign the declaration within the times required for correct performance.",
        ],
      },
      { type: "h2", text: "7. Performance times" },
      { type: "p", text: "Delivery times stated on the site are estimates running from when the client has provided complete, correct documentation validated by the professional. Third-party times (Agency, Cadastre, banks) are excluded." },
      { type: "h2", text: "8. Right of withdrawal (Arts. 52–59 Consumer Code)" },
      {
        type: "ul",
        items: [
          "The consumer may withdraw from the contract within 14 days without giving reasons.",
          "To withdraw, the client may use the sample form or any clear statement sent to the Studio contacts.",
          "Immediate start: if the client expressly asks that work begin during the withdrawal period, once the service is fully performed the right of withdrawal no longer applies.",
          "Withdrawal after start but before completion: the client pays an amount proportional to the service already provided.",
          "Any refund due is made with the same payment method, without undue delay and within legal deadlines.",
        ],
      },
      { type: "callout", tone: "info", text: "We explain withdrawal in plain words on the dedicated page /recesso. This formal text in the Terms is binding." },
      { type: "h2", text: "9. Commercial guarantee \"Satisfied or Refunded\"" },
      { type: "p", text: "The professional may offer, in addition and voluntarily, a refund guarantee under the conditions on the Guarantee page." },
      { type: "h2", text: "10. Limitations of liability" },
      { type: "p", text: "The professional performs the engagement with professional care (obligation of means), with tax supervision by accountants. Liability is limited as provided by law and these Terms." },
      { type: "h2", text: "11. Ownership of documents and access" },
      { type: "p", text: "Final documents (receipts, updated searches, invoice) are made available in the client area. Input documents follow the retention rules in the Privacy notice." },
      { type: "h2", text: "12. Personal data processing" },
      { type: "p", text: "Data processing is described in the Privacy notice on the site, which constitutes an integral part of these Terms." },
      { type: "h2", text: "13. Changes" },
      { type: "p", text: "The professional may amend these Terms; the relationship is governed by the version accepted at purchase, unless changes are required by law." },
      { type: "h2", text: "14. Applicable law, venue and dispute resolution" },
      { type: "p", text: "Italian law applies to the contract. For consumers the mandatory venue of residence remains. Online dispute resolution (ODR) is available via the European platform." },
    ],
  },
  cookie: {
    slug: "cookie",
    title: "Cookie Policy",
    eyebrow: "Legal document",
    intro: "The cookies and similar technologies we use, and how to manage your consents.",
    updatedAt: "Last updated: 14 July 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "What cookies are" },
      { type: "p", text: "Cookies are small text files that sites save on your device to make them work, remember preferences or — with consent — collect statistics." },
      { type: "h2", text: "Categories we use" },
      {
        type: "table",
        headers: ["Category", "What they are for", "Basis / consent"],
        rows: [
          ["Technical / necessary", "Site operation, security, client-area session, language preference storage.", "Always on (no consent required)"],
          ["Analytics (Google Analytics 4)", "Aggregate statistics on how the site is used to improve it. With Consent Mode, tags stay in denied mode until consent.", "Only with prior consent"],
          ["Marketing", "Measuring advertising campaigns and attribution (e.g. Google Ads). Not currently active by default without consent.", "Only with prior consent"],
        ],
      },
      { type: "h2", text: "How you manage consent" },
      { type: "p", text: "On first visit a banner lets you accept or refuse non-essential cookies, with separate choices. You can reopen preferences from the footer." },
      { type: "h2", text: "Disabling in the browser" },
      { type: "p", text: "You can also manage or delete cookies in your browser settings. Disabling technical cookies may limit site functions." },
      { type: "h2", text: "Controller and contacts" },
      { type: "p", text: "Data controller: {{ragione_sociale}}, {{indirizzo}}. Email: {{email}} - PEC: {{pec}}." },
    ],
  },
  garanzia: {
    slug: "garanzia",
    title: "Our guarantee",
    eyebrow: "Your protections",
    intro: "The Satisfied or Refunded promise: an extra protection we offer, beyond your legal rights.",
    updatedAt: "Preliminary version - detailed conditions to be defined",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "The promise" },
      { type: "p", text: "We want you to feel at ease from start to finish. That is why, beyond legal protections (withdrawal), we offer an extra commercial guarantee on our work." },
      { type: "h2", text: "How it works" },
      {
        type: "ol",
        items: [
          "You report the issue by writing to us or from your client area.",
          "We review the situation together, transparently.",
          "If it falls within covered cases, we proceed with a refund using the same payment method, within the stated times.",
        ],
      },
      { type: "callout", tone: "info", title: "Guarantee and withdrawal are two different things", text: "Withdrawal is your legal right in the first 14 days (see Withdrawal page). The guarantee is an extra promise we make on the quality of our work." },
      { type: "h2", text: "What it does not cover" },
      {
        type: "ul",
        items: [
          "Taxes and duties owed to the State (they are not our fee and have no mark-up).",
          "Delays or outcomes due to incorrect, incomplete or late documents from the client.",
          "Times and decisions of third parties (Agenzia delle Entrate, Cadastre, banks).",
        ],
      },
    ],
    cta: { label: "Get a free quote", href: "/preventivo" },
  },
};
