import type { LegalDoc, LegalSlug } from "./legal";

/*
  Turkish courtesy translation of legal documents.
  Italian version is binding — see notice on each document.
  {{tokens}} unchanged (replaced at render-time).
*/

const LANG_NOTE =
  "Bu belgenin İtalyanca sürümü hukuken bağlayıcıdır: her türlü çeviri yalnızca kolaylık içindir ve uyuşmazlık halinde İtalyanca metin geçerlidir.";

const LANG_NOTICE = {
  tone: "info" as const,
  text: LANG_NOTE,
};

export const legalDocsTr: Record<LegalSlug, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "Gizlilik bildirimi",
    eyebrow: "Yasal belge",
    intro: "Siteyi ziyaret ettiğinizde, teklif istediğinizde, hizmet satın aldığınızda veya kişisel alanınızı kullandığınızda kişisel verilerinizi GDPR (AB Reg. 2016/679) uyarınca nasıl işlediğimiz.",
    updatedAt: "Son güncelleme: 14 Temmuz 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "p", text: "Regulation (UE) 2016/679 (\"GDPR\") md. 13 ve 14 ile D.Lgs. 196/2003 (\"Gizlilik Kanunu\") D.Lgs. 101/2018 değişikliği uyarınca Ofis, kişisel verilerin işlenmesine ilişkin aşağıdaki bilgileri sunar." },
      { type: "h2", text: "1. Veri sorumlusu" },
      {
        type: "ul",
        items: [
          "Sorumlu: {{ragione_sociale}} ({{forma_giuridica}})",
          "Faaliyet adresi: {{indirizzo}}",
          "P.IVA: {{piva}} - C.F.: {{cf}}",
          "Meslek sicili kaydı: {{albo}}",
          "PEC: {{pec}} - E-posta: {{email}} - Telefon: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Veri koruma görevlisi (DPO)" },
      { type: "p", text: "Yürütülen faaliyet için DPO atanması zorunlu değildir; değerlendirme Sorumlu tarafından belgelenir ve işlem hacmi ile niteliğine göre güncellenir. Kişisel verilere ilişkin her talep için 1. bölümdeki iletişim bilgilerinden Sorumlu'ya ulaşabilirsiniz." },
      { type: "h2", text: "3. İşlenen veri kategorileri" },
      { type: "p", text: "Etkileşime göre Sorumlu aşağıdaki veri kategorilerini işleyebilir:" },
      {
        type: "ul",
        items: [
          "Kimlik ve iletişim verileri: ad, soyad, e-posta, telefon numarası.",
          "Hizmetle ilgili veriler (veraset dosyası): vergi numarası (C.F.), mirasçı ve vefat edenin kişisel ve mal varlığı verileri, taşınmaz, banka hesapları ve finansal ilişkiler, akrabalık dereceleri.",
          "Belgeler: kimlik belgesi, ölüm belgesi/senedi, tapu kayıtları, onay belgeleri ve dosya için gerekli diğer belgeler.",
          "Ödeme verileri: doğrudan ödeme sağlayıcısı (Stripe) tarafından yönetilir; Sorumlu kartın tam verilerini saklamaz.",
          "Teknik ve gezinme verileri: IP adresi, cihaz tanımlayıcıları, günlükler, çerezler ve benzer teknolojiler (bkz. bölüm 11 ve Çerez Politikası).",
        ],
      },
      { type: "p", text: "Bazı veriler bunları ileten kullanıcıdan başka kişileri ilgilendirebilir (ör. diğer mirasçılar veya vefat eden): ileten kişi bunları iletmeye yetkili olduğunu garanti eder ve ilgilileri bu bilgilendirmeyle bilgilendirmeyi taahhüt eder (GDPR md. 14)." },
      { type: "h2", text: "4. İşleme amaçları ve hukuki dayanaklar" },
      {
        type: "table",
        headers: ["Amaç", "Hukuki dayanak (GDPR)"],
        rows: [
          ["Teklif/iletişim taleplerine yanıt ve sözleşme öncesi faaliyetler", "Md. 6.1.b (sözleşme öncesi önlemler)"],
          ["Mesleki hizmetin ifası (veraset beyanının hazırlanması ve elektronik gönderimi, devirler)", "Md. 6.1.b (sözleşme)"],
          ["Vergi, muhasebe ve saklama yükümlülükleri (fatura, mesleki vekalet)", "Md. 6.1.c (yasal yükümlülük)"],
          ["Ödemelerin yönetimi", "Md. 6.1.b ve 6.1.c"],
          ["Site güvenliği, kötüye kullanım/dolandırıcılık önleme, sistem bütünlüğü", "Md. 6.1.f (meşru menfaat)"],
          ["Doğrudan pazarlama / bülten (etkinleştirilmişse)", "Md. 6.1.a (rıza)"],
          ["Çerezler ve teknik olmayan/profil oluşturma teknolojileri", "Md. 6.1.a (rıza)"],
        ],
      },
      { type: "p", text: "Kural olarak GDPR md. 9 kapsamındaki özel nitelikli veri toplanması öngörülmez. Müşteri gönüllü olarak fazla veri iletirse (ör. bir belgede sağlık bilgisi) Sorumlu bunları md. 9.2 sınırları içinde işler ve minimizasyon önerir." },
      { type: "h2", text: "5. Veri sağlamanın niteliği" },
      { type: "p", text: "Sözleşmesel, vergi ve yasal amaçlar için veri sağlama zorunludur: sağlanmazsa hizmet verilemez. Pazarlama amaçlı sağlama isteğe bağlıdır; red hizmete erişimi etkilemez." },
      { type: "h2", text: "6. İşleme yöntemleri ve güvenlik" },
      { type: "p", text: "Veriler bilişim araçlarıyla ve uygun teknik ve örgütsel önlemlerle işlenir (GDPR md. 32): aktarım ve depolamada şifreleme, erişim kontrolü, Row Level Security ile segmentasyon, minimizasyon ilkesi, erişim kaydı (audit log). Erişim Sorumlu ve yetkili sorumlularla sınırlıdır." },
      { type: "h2", text: "7. Alıcılar ve veri işleyenler" },
      { type: "p", text: "Hizmeti sunmak için Sorumlu, verileri veri işleyen sıfatıyla işleyen tedarikçilerden yararlanır (GDPR md. 28), uygun sözleşmeyle (DPA) bağlıdır. Başlıca kategoriler ve tedarikçiler:" },
      {
        type: "table",
        headers: ["Tedarikçi", "Rol / hizmet", "Veri konumu"],
        rows: [
          ["Supabase", "Veritabanı, kimlik doğrulama, belge depolama", "AB"],
          ["Vercel", "Uygulamanın barındırılması ve dağıtımı", "AB (fonksiyonlar) / AB dışı olası"],
          ["Stripe", "Ödeme işleme", "AB/ABD (SCC)"],
          ["Resend", "İşlemsel e-posta gönderimi", "AB/ABD (SCC)"],
          ["Google Workspace", "Ofisin profesyonel e-postası", "AB/ABD (SCC / DPF)"],
          ["OpenAI", "Dosya belgelerinden verilerin destekli çıkarımı (mesleki faaliyete dahili destek)", "AB/ABD (SCC / DPF)"],
          ["Meta Platforms (WhatsApp Cloud API)", "Mesajlaşma (etkinleştirilmişse)", "AB/ABD (SCC)"],
          ["Google (Analytics/Ads)", "İstatistik ve reklam (yalnızca önceden rıza ile)", "AB/ABD (SCC)"],
          ["Cloudflare (Turnstile)", "Formların kötüye kullanım koruması (etkinleştirilmişse)", "AB/ABD (SCC)"],
        ],
      },
      { type: "p", text: "Veriler ayrıca hizmetin ifası için kamu kurumlarına (ör. Agenzia delle Entrate, Kadastro), gerektiğinde güvenilir meslek mensuplarına (ör. muhasebeci/noter) ve kanunen istenirse adli makamlara/kolluk kuvvetlerine iletilebilir. Veriler üçüncü taraflara kendi bağımsız amaçları için YAYILMAZ veya devredilmez." },
      { type: "h2", text: "8. AB dışına veri aktarımı" },
      { type: "p", text: "Sorumlu, Avrupa Birliği'nde veri barındıran tedarikçileri tercih eder. Bazı tedarikçiler verileri AB dışında (ör. ABD'de) işlediğinde aktarım, GDPR md. 44 ve devamı uyarınca uygun güvencelere dayanır; özellikle Avrupa Komisyonu Standart Sözleşme Maddeleri (SCC) ve/veya yeterlilik kararları (uygulanabildiğinde EU-US Data Privacy Framework)." },
      { type: "h2", text: "9. Saklama süresi" },
      {
        type: "ul",
        items: [
          "Vergi ve muhasebe belgeleri (faturalar, makbuzlar, vekalet, beyan): kanuni süre boyunca, en az 10 yıl (md. 2220 İtalyan Medeni Kanunu ve vergi yükümlülükleri).",
          "Müşterinin yüklediği hassas giriş belgeleri (ör. kimlik kartı): işlem için gerekli süre boyunca saklanır, ardından buluttan silinir (minimizasyon).",
          "Nihai belgeler (AdE makbuzları, güncel tapu kayıtları, fatura): müşterinin kişisel alanında inceleme için sunulur; tam arşiv güvenle saklanır.",
          "Dönüşmeyen teklifler için iletişim verileri: son temastan itibaren 12 ay içinde silinir veya anonimleştirilir.",
          "Pazarlama verileri: rıza geri alınana kadar.",
          "Teknik/günlük veriler ve çerezler: Çerez Politikası'ndaki sürelere göre.",
        ],
      },
      { type: "h2", text: "10. İlgili kişinin hakları" },
      { type: "p", text: "GDPR md. 15-22 kapsamındaki hakları istediğiniz zaman kullanabilirsiniz: erişim, düzeltme, silme (\"unutulma hakkı\", yasal saklama yükümlülükleri sınırları içinde), kısıtlama, taşınabilirlik, meşru menfaate dayalı işlemeye itiraz, rızanın istediğiniz zaman geri alınması (önceki işlemenin hukuka uygunluğunu etkilemez)." },
      { type: "p", text: "Talepler 1. bölümdeki iletişim bilgilerine gönderilmelidir. Sorumlu haksız gecikme olmaksızın ve her halükarda bir ay içinde yanıt verir. Ayrıca Kişisel Verilerin Korunması Garantisi'ne (www.garanteprivacy.it) şikayette bulunma hakkınız vardır." },
      { type: "h2", text: "11. Çerezler ve izleme teknolojileri" },
      { type: "p", text: "Site teknik çerezler kullanır ve önceden rıza ile istatistik çerezleri (Consent Mode ile Google Analytics 4: rıza olmadan ölçüm çerezi ayarlanmaz). Kategoriler, amaçlar ve sürelerin ayrıntısı banner ve alt bilgiden erişilebilen Çerez Politikası'nda yer alır. Rıza alt bilgideki \"Çerez tercihleri\" bağlantısından istediğiniz zaman geri alınabilir." },
      { type: "h2", text: "12. Otomatik karar verme ve yapay zekâ" },
      { type: "p", text: "GDPR md. 22 uyarınca ilgili kişi üzerinde hukuki etki doğuran otomatik karar verme yapılmaz. Ofis yapay zekâ araçlarını yalnızca mesleki faaliyete dahili destek olarak kullanır: dosya için yüklenen belgeler, beyanın hazırlanması için gerekli verileri çıkarmak üzere (ör. kişisel, kadastro verileri) OpenAI API hizmeti (veri işleyen, bkz. bölüm 7) aracılığıyla işlenebilir." },
      {
        type: "ul",
        items: [
          "API ile gönderilen veriler OpenAI tarafından kendi modellerini eğitmek için kullanılmaz.",
          "Çıkarılan her veri kullanımdan önce meslek mensubu tarafından doğrulanır ve onaylanır: nihai karar her zaman insana aittir.",
          "İlgili AB dışı aktarım, 8. bölümdeki güvencelerle yapılır.",
        ],
      },
      { type: "h2", text: "13. Reşit olmayanlar" },
      { type: "p", text: "Hizmetler reşit kişilere yöneliktir. Sorumlu, ebeveyn sorumluluğunu kullananın rızası olmadan bilerek reşit olmayanlara ait veri toplamaz." },
      { type: "h2", text: "14. Bilgilendirmede değişiklikler" },
      { type: "p", text: "Sorumlu bu bilgilendirmeyi güncelleyebilir. Yürürlükteki sürüm her zaman bu sayfada son güncelleme tarihiyle yayımlanır; önemli değişikliklerde uygun şekilde belirtilir." },
    ],
  },
  termini: {
    slug: "termini",
    title: "Satış koşulları",
    eyebrow: "Yasal belge",
    intro: "Mesleki hizmetlerimizin tüketicilere uzaktan satışını düzenleyen şartlar ve koşullar (D.Lgs. 206/2005, Tüketici Kanunu).",
    updatedAt: "Son güncelleme: 14 Temmuz 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "1. Meslek mensubu hakkında bilgi (Tüketici Kanunu md. 49)" },
      {
        type: "ul",
        items: [
          "Meslek mensubu: {{ragione_sociale}} ({{forma_giuridica}})",
          "Faaliyet adresi: {{indirizzo}}",
          "P.IVA: {{piva}} - C.F.: {{cf}}",
          "Meslek sicili kaydı: {{albo}}",
          "PEC: {{pec}} - E-posta: {{email}} - Telefon: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Konu ve uygulama kapsamı" },
      { type: "p", text: "Bu Koşullar, site üzerinden sunulan mesleki hizmetlerin uzaktan satışını düzenler; satın alınan pakete göre veraset beyanının hazırlanması ve elektronik iletilmesi ile bağlantılı yükümlülükler (ör. kadastro devirleri)." },
      { type: "p", text: "Agenzia delle Entrate'e elektronik gönderim, uygun vekalet/görevlendirme ve müşterinin imzaladığı beyanın alınmasından sonra meslek mensubu tarafından ENTRATEL yetkili aracı sıfatıyla yapılır. Sözleşme uzaktan, elektronik yolla kurulur." },
      { type: "h2", text: "3. Paketler, fiyatlar ve istisnalar" },
      { type: "p", text: "Paketler ve ilgili fiyatlar (ücret) Tarifeler sayfasında belirtilir. Gösterilen fiyat yalnızca mesleki ücrete ilişkindir." },
      { type: "callout", tone: "warning", title: "Ücret ve vergiler farklı şeylerdir", text: "Devlete ödenmesi gereken vergi ve harçlar (ör. öz-beyan veraset vergisi, ipotek, kadastro, damga, özel harçlar) hizmet fiyatına DAHİL DEĞİLDİR: somut duruma göre hesaplanır, gönderimden önce müşteriye bildirilir ve mirasçı tarafından ödenir. Meslek mensubu bu tutarlara herhangi bir ek ücret uygulamaz." },
      {
        type: "ul",
        items: [
          "Aksi kararlaştırılmadıkça pakete dahil olmayan hizmetler (ör. dava, noter işlemleri, karmaşık vergi danışmanlığı, basit olmayan haller) hariçtir. Ek faaliyetler ayrıca teklif edilir.",
          "Kişiselleştirilmiş teklif (karmaşık haller): doğası veya karmaşıklığı standart paketleri aşan dosyalar (ör. çoklu taşınmaz, tarla/tarım parselleri, şirket payları, vasiyetname ile veraset, yurt dışı mirasçılar, belge temini) için fiyat satın almadan önce bildirilen bireysel teklifle belirlenir.",
          "Çevrimiçi anket sonucu önerilen paket gösterge niteliğindedir: belgelerin kontrolünden sonra değişiklik ve mahsuplaşma prosedürü (md. 5) uygulanabilir.",
          "Zorunluluk olmama ön kontrolü: verilen bilgilerden beyanın kanunen gerekli olmadığı anlaşılırsa meslek mensubu müşteriye bildirir; kesin değerlendirme somut olayın incelenmesini gerektirir.",
        ],
      },
      { type: "h2", text: "4. Sözleşmenin kurulması" },
      { type: "p", text: "Teklif talebi bağlayıcı değildir. Sözleşme paket ödemesi ve ödeme sırasında bu Koşulların açık kabulüyle tamamlanır. Satın almadan önce müşteri hizmetin özelliklerini, toplam fiyatı, bu Koşulları ve gizlilik bilgilendirmesini inceler." },
      { type: "h2", text: "5. Ödeme ve paket değişikliği" },
      { type: "p", text: "Ücret ödemesi ödeme sağlayıcısı (Stripe) aracılığıyla peşin yapılır. Fatura yürürlükteki yükümlülüklere göre düzenlenir. Devlet vergileri ayrı yönetilir ve bildirilen şekilde mirasçı tarafından ödenir." },
      { type: "p", text: "Paket değişikliği ve mahsuplaşma: müşteriyle anlaşmayla paket değiştirilirse fark mahsuplaştırılır. Üst pakete geçişte müşteri farkı ödeme bağlantısıyla tamamlar; alt pakete geçişte ödenen fark aynı yöntemle gecikmeksizin iade edilir. Değişiklik kalıcı ortamda onaylanır. Devlet vergileri her durumda mahsuplaşmaya dahil değildir." },
      { type: "h2", text: "6. Müşterinin yükümlülükleri ve sorumluluğu" },
      {
        type: "ul",
        items: [
          "Müşteri doğru, eksiksiz ve zamanında veri ve belge sağlar; doğruluğundan sorumludur.",
          "Meslek mensubu, müşteriden gelen hatalı, eksik veya geç bilgi/belgelerden kaynaklanan gecikme, hata veya cezalardan; üçüncü kurumların (Agenzia delle Entrate, Kadastro, bankalar) işlem sürelerinden sorumlu değildir.",
          "Müşteri vekalet vermeyi ve beyanı istenen süreler içinde imzalamayı taahhüt eder.",
        ],
      },
      { type: "h2", text: "7. İfa süreleri" },
      { type: "p", text: "Sitede belirtilen teslim süreleri, müşterinin gerekli tüm belgeleri eksiksiz, doğru ve meslek mensubu tarafından onaylanmış şekilde sağladığı andan itibaren (ödeme tarihinden değil) başlayan tahminlerdir; üçüncü kurum süreleri dahil değildir. Belgeler eksik veya tamamlama bekliyorsa süre askıda kalır; son eksik belgenin alınması/onaylanmasıyla devam eder." },
      { type: "h2", text: "8. Cayma hakkı (Tüketici Kanunu md. 52-59)" },
      {
        type: "ul",
        items: [
          "Tüketici gerekçe göstermeksizin 14 gün içinde sözleşmeden cayabilir; hizmetlerde süre sözleşmenin kurulmasından itibaren işler.",
          "Cayma için müşteri örnek formu veya 1. bölümdeki iletişim bilgilerine gönderilen açık bir beyanı kullanabilir. Meslek mensubu alımı gecikmeksizin onaylar.",
          "Derhal başlangıç: müşteri cayma süresi içinde işlemin başlamasını açıkça isterse, derhal başlamaya açık rıza verir ve hizmet tamamen ifa edildiğinde cayma hakkını kaybettiğini kabul eder (md. 59, f.1, bent a).",
          "Başlangıçtan sonra tamamlanmadan önce cayma: müşteri cayma bildirimine kadar ifa edilen hizmete orantılı tutarı öder (md. 57, f.3).",
          "Gerekirse iade aynı ödeme yöntemiyle, gecikmeksizin ve her halükarda 14 gün içinde yapılır.",
        ],
      },
      { type: "callout", tone: "info", text: "Caymayı /recesso sayfasında sade bir dille açıklıyoruz. Bağlayıcı resmi metin budur." },
      { type: "h2", text: "9. \"Memnun kalmazsanız iade\" ticari garantisi" },
      { type: "p", text: "Meslek mensubu, ek ve gönüllü olarak, Garanti sayfasındaki koşullarda iade garantisi sunabilir. Bu garanti ek niteliktedir ve tüketicinin kanuni haklarını sınırlamaz." },
      { type: "h2", text: "10. Sorumluluk sınırlamaları" },
      { type: "p", text: "Meslek mensubu görevi mesleki özenle yerine getirir (araç borcu). Kast veya ağır kusur hariç ve kanuni sınırlar içinde sorumluluk, dosya için ödenen ücret tutarıyla sınırlıdır. Meslek mensubu üçüncü kişilere, mücbir sebebe veya dış tedarikçi arızalarına atfedilebilir olaylardan sorumlu değildir." },
      { type: "h2", text: "11. Belgelerin mülkiyeti ve erişim" },
      { type: "p", text: "Nihai belgeler (makbuzlar, güncel tapu kayıtları, fatura) belirtilen sürelerde müşterinin kişisel alanında inceleme ve indirme için sunulur. Saklama gizlilik bilgilendirmesine göre düzenlenir." },
      { type: "h2", text: "12. Kişisel verilerin işlenmesi" },
      { type: "p", text: "Veri işleme, sitede yer alan ve ilişkinin ayrılmaz parçasını oluşturan Gizlilik Bilgilendirmesi'nde açıklanır." },
      { type: "h2", text: "13. Değişiklikler" },
      { type: "p", text: "Meslek mensubu bu Koşulları değiştirebilir; ilişkiye satın alma anında kabul edilen sürüm uygulanır. Yürürlükteki sürüm her zaman sitede yayımlanır." },
      { type: "h2", text: "14. Uygulanacak hukuk, yetki ve uyuşmazlık çözümü" },
      { type: "p", text: "Sözleşmeye İtalyan hukuku uygulanır. Tüketiciler için ikamet/domicil yetkisi değiştirilemez. Şikayetler 1. bölümdeki iletişim bilgilerine. Tüketici Avrupa ODR platformuna (https://ec.europa.eu/consumers/odr) ve yetkili arabuluculuk/ADR kurumlarına başvurabilir." },
    ],
  },
  cookie: {
    slug: "cookie",
    title: "Çerez Politikası",
    eyebrow: "Yasal belge",
    intro: "Kullandığımız çerezler ve benzer teknolojiler ile rızalarınızı nasıl yönettiğimiz.",
    updatedAt: "Son güncelleme: 14 Temmuz 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Çerezler nedir" },
      { type: "p", text: "Çerezler, sitelerin cihazınıza kaydettiği küçük metin dosyalarıdır; siteyi çalıştırmak, tercihlerinizi hatırlamak veya istatistik toplamak için kullanılır. Çerezlerle birlikte benzer teknolojiler de kullanırız (ör. local storage, piksel)." },
      { type: "h2", text: "Kullandığımız kategoriler" },
      {
        type: "table",
        headers: ["Kategori", "Ne işe yarar", "Dayanak / rıza"],
        rows: [
          ["Teknik / gerekli", "Site işleyişi, güvenlik, kişisel alan oturumu, çerez tercihlerinin saklanması.", "Her zaman açık (rıza gerekmez)"],
          ["Analitik (Google Analytics 4)", "Siteyi geliştirmek için toplu istatistikler. Consent Mode sayesinde rızanız olmadan ölçüm çerezi ayarlanmaz.", "Yalnızca önceden rıza ile"],
          ["Pazarlama", "Reklam kampanyalarının ölçümü ve atıf (ör. Google Ads). Şu an etkin değil: etkinleştirilirse banner'dan rıza gerekecektir.", "Yalnızca önceden rıza ile"],
        ],
      },
      { type: "h2", text: "Rızayı nasıl yönetirsiniz" },
      { type: "p", text: "İlk ziyarette banner, gerekli olmayan çerezleri eşit görünürlükte kabul veya reddetmenize izin verir. Alt bilgideki \"Çerez tercihleri\" bağlantısından rızayı istediğiniz zaman değiştirebilir veya geri alabilirsiniz; geri alma önceki işlemenin hukuka uygunluğunu etkilemez." },
      { type: "h2", text: "Tarayıcıdan devre dışı bırakma" },
      { type: "p", text: "Çerezleri tarayıcı ayarlarından da yönetebilir veya silebilirsiniz. Teknik çerezlerin kapatılması bazı site işlevlerini (ör. kişisel alan erişimi) etkileyebilir." },
      { type: "h2", text: "Sorumlu ve iletişim" },
      { type: "p", text: "Veri sorumlusu: {{ragione_sociale}}, {{indirizzo}}. E-posta: {{email}} - PEC: {{pec}}. Kişisel verilerin işlenmesine ilişkin ayrıntılar için Gizlilik Bilgilendirmesi'ne bakın." },
    ],
  },
  garanzia: {
    slug: "garanzia",
    title: "Garantimiz",
    eyebrow: "Haklarınız",
    intro: "Memnun kalmazsanız iade sözü: kanuni haklarınıza ek olarak sunduğumuz ek koruma.",
    updatedAt: "Ön sürüm - ayrıntılı koşullar tanımlanacak",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Sözümüz" },
      { type: "p", text: "Baştan sona içinizin rahat olmasını istiyoruz. Bu nedenle kanuni korumalara ek olarak gönüllü \"Memnun kalmazsanız iade\" garantisi sunuyoruz: anlaştığımız gibi gitmezse konuşur ve çözüm buluruz, öngörülen hallerde iadeye kadar." },
      { type: "h2", text: "Nasıl çalışır" },
      {
        type: "ol",
        items: [
          "Sorunu bize yazarak veya kişisel alanınızdan bildirirsiniz.",
          "Durumu birlikte şeffaf biçimde inceleriz.",
          "Kapsanan hallerden biriyse aynı ödeme yöntemiyle, belirtilen sürelerde iade yaparız. (Belirli haller, tutarlar ve süreler: tanımlanacak.)",
        ],
      },
      { type: "callout", tone: "info", title: "Garanti ve cayma farklı şeylerdir", text: "Cayma ilk 14 günde kanuni hakkınızdır (Cayma sayfasına bakın). Memnun kalmazsanız iade garantisi ek, gönüllü bir ticari sözüdür; tüketici haklarınızı hiçbir şekilde sınırlamaz." },
      { type: "h2", text: "Neleri kapsamaz" },
      {
        type: "ul",
        items: [
          "Devlete ödenmesi gereken vergi ve harçlar (bizim ücretimiz değildir ve ek ücret uygulanmaz).",
          "Müşteriden gelen hatalı, eksik veya geç belgelere bağlı gecikme veya sonuçlar.",
          "Üçüncü kurumların (Agenzia delle Entrate, Kadastro, bankalar) süreleri ve kararları.",
        ],
      },
    ],
    cta: { label: "Ücretsiz ön teklif hesapla", href: "/preventivo" },
  },
};
