import type { LegalDoc, LegalSlug } from "./legal";

/*
  Hindi courtesy translation of legal documents.
  Italian version is binding — see notice on each document.
  {{tokens}} unchanged (replaced at render-time).
*/

const LANG_NOTE =
  "इस दस्तावेज़ का इतालवी संस्करण कानूनी रूप से बाध्यकारी है: कोई भी अनुवाद केवल सुविधा के लिए है और विवाद की स्थिति में इतालवी पाठ मान्य होगा।";

const LANG_NOTICE = {
  tone: "info" as const,
  text: LANG_NOTE,
};

export const legalDocsHi: Record<LegalSlug, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "गोपनीयता सूचना",
    eyebrow: "कानूनी दस्तावेज़",
    intro: "साइट, अनुमान, सेवा या व्यक्तिगत क्षेत्र उपयोग पर GDPR (Reg. UE 2016/679) अनुसार डेटा उपचार।",
    updatedAt: "अंतिम अपडेट: 14 जुलाई 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "p", text: "GDPR (Reg. UE 2016/679) अनु. 13-14 और D.Lgs. 196/2003 (Codice Privacy), D.Lgs. 101/2018 संशोधित — Studio व्यक्तिगत डेटा उपचार सूचना।" },
      { type: "h2", text: "1. उपचार नियंत्रक" },
      {
        type: "ul",
        items: [
          "नियंत्रक: {{ragione_sociale}} ({{forma_giuridica}})",
          "परिचालन कार्यालय: {{indirizzo}}",
          "P.IVA: {{piva}} - Codice Fiscale: {{cf}}",
          "Albo पंजीकरण: {{albo}}",
          "PEC: {{pec}} - Email: {{email}} - Telefono: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. DPO" },
      { type: "p", text: "DPO नियुक्ति इस गतिविधि के लिए बाध्य नहीं; Titolare दस्तावेज़ी मूल्यांकन, volume/प्रकृति अनुसार अपडेट। डेटा अनुरोध: §1 संपर्क।" },
      { type: "h2", text: "3. उपचारित डेटा श्रेणियाँ" },
      { type: "p", text: "interaction अनुसार Titolare ये श्रेणियाँ:" },
      {
        type: "ul",
        items: [
          "पहचान/संपर्क: नाम, ईमेल, फ़ोन।",
          "सेवा (उत्तराधिकार फ़ाइल): codice fiscale, उत्तराधिकारी/मृतक व्यक्तिगत/संपत्ति, immobili, खाते, रिश्ता।",
          "दस्तावेज़: ID, मृत्यु प्रमाण, visure, प्रमाण और अन्य।",
          "भुगतान: Stripe (Titolare पूर्ण कार्ड नहीं रखता)।",
          "तकनीकी: IP, device ID, log, cookie (§11, Cookie Policy)।",
        ],
      },
      { type: "p", text: "कुछ डेटा अन्य (उत्तराधिकारी/मृतक): प्रदानकर्ता legitimation और art. 14 GDPR सूचना।" },
      { type: "h2", text: "4. उद्देश्य और कानूनी आधार" },
      {
        type: "table",
        headers: ["उद्देश्य", "कानूनी आधार (GDPR)"],
        rows: [
          ["अनुमान/संपर्क और precontractual", "Art. 6.1.b (precontractual)"],
          ["पेशेवर सेवा (उत्तराधिकार घोषणा telematica, volture)", "Art. 6.1.b (contract)"],
          ["कर/लेखा/संरक्षण (चालान, अधिदेश)", "Art. 6.1.c (legal)"],
          ["भुगतान", "Art. 6.1.b और 6.1.c"],
          ["साइट सुरक्षा, दुरुपयोग/धोखाधड़ी", "Art. 6.1.f (legitimate interest)"],
          ["Marketing/newsletter (यदि)", "Art. 6.1.a (consent)"],
          ["गैर-तकनीकी/profiling cookie", "Art. 6.1.a (consent)"],
        ],
      },
      { type: "p", text: "सामान्यतः art. 9 विशेष श्रेणी नहीं। अतिरिक्त (जैसे स्वास्थ्य) art. 9.2 सीमा, minimization।" },
      { type: "h2", text: "5. प्रदान की प्रकृति" },
      { type: "p", text: "अनुबंध/कर/कानूनी उद्देश्य: डेटा आवश्यक, न देने पर सेवा नहीं। Marketing वैकल्पिक, अस्वीकार सेवा access नहीं रोकता।" },
      { type: "h2", text: "6. उपचार और सुरक्षा" },
      { type: "p", text: "IT उपकरण, art. 32 उपाय: transit/rest encryption, access control, RLS, minimization, audit log। Titolare और authorized only।" },
      { type: "h2", text: "7. प्राप्तकर्ता और processors" },
      { type: "p", text: "सेवा हेतु processors (art. 28 GDPR, DPA):" },
      {
        type: "table",
        headers: ["प्रदाता", "भूमिका / सेवा", "डेटा स्थान"],
        rows: [
          ["Supabase", "Database, auth, document storage", "UE"],
          ["Vercel", "ऐप hosting और वितरण", "UE (functions) / संभव extra-UE"],
          ["Stripe", "भुगतान processing", "UE/USA (SCC)"],
          ["Resend", "Transactional email", "UE/USA (SCC)"],
          ["Google Workspace", "Studio professional email", "UE/USA (SCC / DPF)"],
          ["OpenAI", "फ़ाइल दस्तावेज़ों से assisted data extraction (पेशेवर internal support)", "UE/USA (SCC / DPF)"],
          ["Meta Platforms (WhatsApp Cloud API)", "Messaging (यदि active)", "UE/USA (SCC)"],
          ["Google (Analytics/Ads)", "Statistics और advertising (consent पर)", "UE/USA (SCC)"],
          ["Cloudflare (Turnstile)", "Form anti-abuse (यदि active)", "UE/USA (SCC)"],
        ],
      },
      { type: "p", text: "डेटा public entities (Agenzia delle Entrate, Catasto), trusted professionals (commercialista/notaio), judicial/police — law पर — को भी। तретीय parties को autonomous purposes के लिए नहीं।" },
      { type: "h2", text: "8. extra-UE डेटा transfer" },
      { type: "p", text: "Titolare EU providers prefer। extra-UE (USA) पर art. 44+ GDPR guarantees, SCC और/या adequacy (EU-US DPF)।" },
      { type: "h2", text: "9. retention period" },
      {
        type: "ul",
        items: [
          "कर/लेखा docs (invoice, receipt, mandate, declaration): legal term, min 10 years (art. 2220 c.c.)।",
          "Sensitive client input (ID): processing time, फिर cloud delete (minimization)।",
          "Final docs (AdE receipts, updated visure, invoice): व्यक्तिगत क्षेत्र consultation; secure archive।",
          "Unconverted quote contacts: 12 months delete/anonymize।",
          "Marketing: consent revoke तक।",
          "Technical/log/cookie: Cookie Policy durations।",
        ],
      },
      { type: "h2", text: "10. data subject rights" },
      { type: "p", text: "art. 15-22 GDPR: access, rectification, erasure (oblio limits), restriction, portability, opposition, consent revoke।" },
      { type: "p", text: "§1 contacts पर requests। 1 month response। Garante complaint (www.garanteprivacy.it)।" },
      { type: "h2", text: "11. Cookie और tracking" },
      { type: "p", text: "Technical cookies; consent पर statistics (GA4 Consent Mode)। Cookie Policy banner/footer। \"Preferenze cookie\" revoke।" },
      { type: "h2", text: "12. स्वचालित निर्णय और कृत्रिम बुद्धिमत्ता" },
      { type: "p", text: "GDPR अनुच्छेद 22 के अर्थ में कोई स्वचालित निर्णय नहीं लिया जाता जो उपयोगकर्ता पर कानूनी प्रभाव डाले। AI केवल पेशेवर के आंतरिक समर्थन के लिए है; OpenAI API (§7) दस्तावेज़ों से डेटा निकालने में सहायक है (anagrafici, catastali)।" },
      {
        type: "ul",
        items: [
          "API के माध्यम से भेजे गए डेटा का उपयोग OpenAI अपने मॉडल के प्रशिक्षण के लिए नहीं करता।",
          "निकाले गए प्रत्येक डेटा की पेशेवर द्वारा जाँच होती है: अंतिम निर्णय मानव का रहता है।",
          "संबंधित गैर-EU स्थानांतरण §8 की सुरक्षाओं के साथ होते हैं।",
        ],
      },
      { type: "h2", text: "13. नाबालिग" },
      { type: "p", text: "सेवाएँ वयस्कों के लिए हैं। नियंत्रक जानबूझकर माता-पिता की भागीदारी के बिना नाबालिगों का डेटा एकत्र नहीं करता।" },
      { type: "h2", text: "14. इस सूचना में परिवर्तन" },
      { type: "p", text: "नियंत्रक इस सूचना को अद्यतन कर सकता है। वर्तमान संस्करण सदैव साइट पर अद्यतन तिथि के साथ प्रकाशित रहता है।" },
    ],
  },
  termini: {
    slug: "termini",
    title: "बिक्री की शर्तें",
    eyebrow: "कानूनी दस्तावेज़",
    intro: "उपभोक्ताओं को दी जाने वाली हमारी पेशेवर सेवाओं की दूरस्थ बिक्री को नियंत्रित करने वाले नियम और शर्तें (D.Lgs. 206/2005, Cod. Consumo)।",
    updatedAt: "अंतिम अपडेट: 14 जुलाई 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "1. पेशेवर के बारे में जानकारी (art. 49 Cod. Consumo)" },
      {
        type: "ul",
        items: [
          "पेशेवर: {{ragione_sociale}} ({{forma_giuridica}})",
          "परिचालन कार्यालय: {{indirizzo}}",
          "P.IVA: {{piva}} - Codice Fiscale: {{cf}}",
          "Albo पंजीकरण: {{albo}}",
          "PEC: {{pec}} - Email: {{email}} - Telefono: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. विषय और लागू क्षेत्र" },
      { type: "p", text: "ये शर्तें साइट के माध्यम से प्रस्तावित पेशेवर सेवाओं की दूरस्थ बिक्री को नियंत्रित करती हैं, जिनमें उत्तराधिकार घोषणा की तैयारी और telematica प्रेषण तथा संबंधित कार्य (जैसे volture catastali) शामिल हैं, खरीदे गए पैकेज के अनुसार।" },
      { type: "p", text: "Agenzia delle Entrate को telematica प्रेषण पेशेवर ENTRATEL-अधिकृत मध्यस्थ के रूप में करता है, उपयुक्त अधिदेश/कार्य प्राप्त करने और ग्राहक द्वारा हस्ताक्षरित घोषणा मिलने के बाद। अनुबंध दूरस्थ रूप से electronic माध्यम से संपन्न होता है।" },
      { type: "h2", text: "3. पैकेज, कीमतें और अपवाद" },
      { type: "p", text: "पैकेज और संबंधित कीमतें (onorario) Tariffe पृष्ठ पर दर्शाई गई हैं। दर्शाई गई कीमत केवल पेशेवर onorario पर लागू होती है।" },
      { type: "callout", tone: "warning", title: "Onorario और कर अलग-अलग हैं", text: "राज्य को देय कर और tributi (जैसे self-assessed उत्तराधिकार कर, mortgage/cadastral कर, stamp, special tributi) सेवा की कीमत में शामिल नहीं हैं: वे विशिष्ट स्थिति के अनुसार गणना की जाती हैं, प्रेषण से पहले ग्राहक को सूचित की जाती हैं और उत्तराधिकारी द्वारा भुगतान की जाती हैं। पेशेवर इन राशियों पर कोई अतिरिक्त शुल्क नहीं लगाता।" },
      {
        type: "ul",
        items: [
          "जब तक अन्यथा सहमति न हो, पैकेज में वे सेवाएँ शामिल नहीं हैं जो स्पष्ट रूप से निर्दिष्ट नहीं हैं (जैसे विवाद, notarial कार्य, जटिल कर परामर्श, non-linear मामले)। अतिरिक्त कार्य अलग से quote किए जाते हैं।",
          "व्यक्तिगत अनुमान (जटिल मामले): जिन मामलों की प्रकृति या जटिलता standard पैकेज से अधिक है (जैसे कई immobili, agricultural भूमि/particelle, company shares, testamentary succession, विदेश में heirs, document recovery), कीमत खरीद से पहले individual quote से तय होती है।",
          "ऑनलाइन प्रश्नावली के बाद प्रस्तावित पैकेज संकेतात्मक है: दस्तावेज़ जाँच के बाद modification और conguaglio (art. 5) procedure लागू हो सकती है।",
          "Non-obligation प्रारंभिक जाँच: यदि प्रदान data से घोषणा कानूनी रूप से आवश्यक नहीं दिखती, पेशेवर ग्राहक को सूचित करता है; अंतिम मूल्यांकन concrete case के अध्ययन पर निर्भर करता है।",
        ],
      },
      { type: "h2", text: "4. अनुबंध की स्थापना" },
      { type: "p", text: "अनुमान का अनुरोध बाध्यकारी नहीं है। अनुबंध पैकेज के भुगतान और checkout पर इन शर्तों की स्पष्ट स्वीकृति से संपन्न होता है। खरीद से पहले ग्राहक सेवा की विशेषताएँ, कुल कीमत, ये शर्तें और गोपनीयता सूचना देखता है।" },
      { type: "h2", text: "5. भुगतान और पैकेज में परिवर्तन" },
      { type: "p", text: "onorario का भुगतान Stripe के माध्यम से अग्रिम में किया जाता है। चालान लागू obligations के अनुसार जारी होती है। राज्य के कर अलग manage होते हैं और उत्तराधिकारी सूचित methods से भुगतान करता है।" },
      { type: "p", text: "पैकेज में परिवर्तन और conguaglio: ग्राहक की सहमति से पैकेज बदलने पर अंतर का conguaglio होता है। उच्च पैकेज पर ग्राहक payment link से अंतर भरता है; निम्न पैकेज पर पहले से भुगतान अंतर same method से वापस, बिना delay। परिवर्तन durable medium पर confirm होता है। राज्य के कर conguaglio से excluded रहते हैं।" },
      { type: "h2", text: "6. ग्राहक के दायित्व और जिम्मेदारी" },
      {
        type: "ul",
        items: [
          "ग्राहक सही, पूर्ण और समय पर data और documents प्रदान करता है और उनकी शुद्धता के लिए जिम्मेदार है।",
          "पेशेवर ग्राहक की गलत, अपूर्ण या विलंबित information/documents, या तृतीय-party processing times (Agenzia delle Entrate, Catasto, banks) से उत्पन्न delays, errors या sanctions के लिए जिम्मेदार नहीं है।",
          "ग्राहक required terms में mandate देने और declaration पर हस्ताक्षर करने का commitment देता है।",
        ],
      },
      { type: "h2", text: "7. निष्पादन समय" },
      { type: "p", text: "साइट पर दर्शाए delivery समय estimates हैं, payment की तारीख से नहीं बल्कि तब से जब ग्राहक ने सभी आवश्यक, पूर्ण, सही documentation पेशेवर द्वारा validated प्रदान की; third-party times excluded। जब तक documentation incomplete है term suspended रहता है और last missing document validate होने पर resume होता है।" },
      { type: "h2", text: "8. recesso का अधिकार (artt. 52-59 Cod. Consumo)" },
      {
        type: "ul",
        items: [
          "उपभोक्ता को 14 दिनों में बिना कारण बताए अनुबंध से recesso करने का अधिकार है; services के लिए अवधि contract conclusion से count होती है।",
          "Recesso exercise करने के लिए ग्राहक model form या §1 contacts पर explicit declaration भेज सकता है। पेशेवर receipt की बिना delay confirmation देता है।",
          "तत्काल start: यदि ग्राहक recesso period में work start करने का explicit request करता है, immediate start की explicit consent देता है और acknowledge करता है कि service fully performed होने पर recesso right खो जाता है (art. 59 §1 a)।",
          "Start के बाद completion से पहले recesso: ग्राहक recesso notice तक already rendered service के proportional amount का payment करता है (art. 57 §3)।",
          "Due refund same payment method से, बिना undue delay, अधिकतम 14 दिनों में।",
        ],
      },
      { type: "callout", tone: "info", text: "हम recesso को सरल शब्दों में /recesso पृष्ठ पर समझाते हैं। यह औपचारिक पाठ binding है।" },
      { type: "h2", text: "9. commercial guarantee \"Soddisfatti o Rimborsati\"" },
      { type: "p", text: "पेशेवर Garanzia पृष्ठ पर दी गई conditions के अनुसार स्वैच्छिक रूप से refund guarantee offer कर सकता है। यह guarantee additional है और consumer के legal rights limit नहीं करती।" },
      { type: "h2", text: "10. जिम्मेदारी की सीमाएँ" },
      { type: "p", text: "पेशेवर professional diligence (means obligation) के साथ engagement execute करता है। dolo या gross negligence को छोड़कर और law limits में, liability practice के paid onorario तक capped। third parties, force majeure या external provider failures से जुड़े events के लिए responsible नहीं।" },
      { type: "h2", text: "11. दस्तावेज़ों का स्वामित्व और access" },
      { type: "p", text: "अंतिम दस्तावेज़ (रसीदें, अद्यतन visure, चालान) ग्राहक के व्यक्तिगत क्षेत्र में consultation और download के लिए निर्दिष्ट समय तक उपलब्ध कराए जाते हैं। retention गोपनीयता सूचना द्वारा regulated है।" },
      { type: "h2", text: "12. व्यक्तिगत डेटा उपचार" },
      { type: "p", text: "डेटा processing Informativa Privacy में described है, relationship का integral part।" },
      { type: "h2", text: "13. संशोधन" },
      { type: "p", text: "पेशेवर ये शर्तें modify कर सकता है; relationship purchase पर accepted version governed होता है। current version हमेशा साइट पर published।" },
      { type: "h2", text: "14. लागू कानून, forum और disputes" },
      { type: "p", text: "अनुबंध पर Italian law लागू होती है। consumers residence/domicile mandatory forum preserved। complaints §1 contacts। consumer European ODR platform (https://ec.europa.eu/consumers/odr) और competent ADR/mediatio bodies का उपयोग कर सकता है।" },
    ],
  },
  cookie: {
    slug: "cookie",
    title: "Cookie Policy",
    eyebrow: "कानूनी दस्तावेज़",
    intro: "हम जो cookies और समान technologies उपयोग करते हैं, और अपनी सहमति कैसे प्रबंधित करें।",
    updatedAt: "अंतिम अपडेट: 14 जुलाई 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Cookies क्या हैं" },
      { type: "p", text: "Cookies छोटी text files हैं जो sites आपके device पर save करती हैं ताकि site काम करे, preferences याद रखे या — consent के साथ — statistics collect करे। Cookies के साथ similar technologies (local storage, pixel) भी use करते हैं।" },
      { type: "h2", text: "हम जिन categories use करते हैं" },
      {
        type: "table",
        headers: ["श्रेणी", "उद्देश्य", "आधार / सहमति"],
        rows: [
          ["तकनीकी / आवश्यक", "साइट का काम, सुरक्षा, व्यक्तिगत क्षेत्र सत्र, कुकी विकल्पों का संग्रह।", "हमेशा सक्रिय (सहमति नहीं)"],
          ["विश्लेषणात्मक (Google Analytics 4)", "साइट उपयोग के समग्र आँकड़े। Consent Mode: सहमति के बिना measurement cookie नहीं।", "केवल सहमति पर"],
          ["मार्केटिंग", "विज्ञापन अभियान मापन (Google Ads)। वर्तमान में निष्क्रिय; सक्रिय होने पर बैनर सहमति आवश्यक।", "केवल सहमति पर"],
        ],
      },
      { type: "h2", text: "सहमति कैसे प्रबंधित करें" },
      { type: "p", text: "पहली visit पर banner non-necessary cookies accept/reject equal visibility के साथ choose करने देता है। footer \"Preferenze cookie\" link से anytime consent modify/revoke; revoke prior processing की lawfulness affect नहीं करता।" },
      { type: "h2", text: "Browser से disable" },
      { type: "p", text: "Browser settings से cookies manage/delete कर सकते हैं। technical cookies disable करने पर site functions compromise हो सकती हैं (जैसे व्यक्तिगत क्षेत्र access)।" },
      { type: "h2", text: "Controller और contacts" },
      { type: "p", text: "Processing controller: {{ragione_sociale}}, {{indirizzo}}। Email: {{email}} - PEC: {{pec}}। personal data processing detail Informativa privacy में।" },
    ],
  },
  garanzia: {
    slug: "garanzia",
    title: "हमारी गारंटी",
    eyebrow: "आपकी सुरक्षा",
    intro: "\"Soddisfatti o Rimborsati\" वादा: कानूनी अधिकारों से परे extra सुरक्षा jo hum offer karte hain।",
    updatedAt: "प्रारंभिक version — detail conditions define karne pending hain",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "वादा" },
      { type: "p", text: "हम चाहते हैं कि आप शुरू से अंत तक assured रहें। legal protections ke beyond, voluntarily \"Soddisfatti o Rimborsati\" guarantee offer karte hain: agreed terms ke anusar na ho to solution discuss karte hain, covered cases mein refund tak।" },
      { type: "h2", text: "यह कैसे काम करता है" },
      {
        type: "ol",
        items: [
          "समस्या humein likhkar ya vyaktigat kshetra se report karein।",
          "साथ में स्थिति ko पारदर्शी रूप से verify karte hain।",
          "Covered cases mein same payment method se refund, stated timing mein (specifics define karne hain)।",
        ],
      },
      { type: "callout", tone: "info", title: "Garanzia aur recesso alag cheezen hain", text: "Recesso aapka legal adhikar pehle 14 din hai (/recesso page)। Soddisfatti o Rimborsati extra voluntary commercial promise hai jo consumer rights limit nahi karti।" },
      { type: "h2", text: "क्या covered नहीं है" },
      {
        type: "ul",
        items: [
          "राज्य को dey kar/tributi (hamara onorario nahi, markup nahi)।",
          "Client ke galat/apurn/vilambit documents se delays/outcomes।",
          "Third-party times/decisions (Agenzia delle Entrate, Catasto, banks)।",
        ],
      },
    ],
    cta: { label: "मुफ़्त अनुमान प्राप्त करें", href: "/preventivo" },
  },
};
