import type { LegalDoc, LegalSlug } from "./legal";

/*
  German courtesy translation of legal documents.
  Italian version is binding — see notice on each document.
  {{tokens}} unchanged (replaced at render-time).
*/

const LANG_NOTE =
  "Die italienische Fassung dieses Dokuments ist rechtlich verbindlich: jede Übersetzung dient nur der Orientierung; bei Widersprüchen gilt der italienische Text.";

const LANG_NOTICE = {
  tone: "info" as const,
  text: LANG_NOTE,
};

export const legalDocsDe: Record<LegalSlug, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "Datenschutzerklärung",
    eyebrow: "Rechtsdokument",
    intro: "Wie wir Ihre personenbezogenen Daten verarbeiten beim Besuch der Website, Kostenvoranschlag, Kauf oder Nutzung des Persönlichen Bereichs gemäß DSGVO (EU-VO 2016/679).",
    updatedAt: "Letzte Aktualisierung: 14. Juli 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "p", text: "Gemäß Art. 13 und 14 der Verordnung (EU) 2016/679 („DSGVO“) und D.Lgs. 196/2003 („Privacy-Kodex“) i. d. F. D.Lgs. 101/2018 informiert das Studio über die Verarbeitung personenbezogener Daten." },
      { type: "h2", text: "1. Verantwortlicher" },
      {
        type: "ul",
        items: [
          "Verantwortlicher: {{ragione_sociale}} ({{forma_giuridica}})",
          "Betriebsadresse: {{indirizzo}}",
          "P.IVA: {{piva}} - C.F.: {{cf}}",
          "Kammereintragung: {{albo}}",
          "PEC: {{pec}} - E-Mail: {{email}} - Telefon: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Datenschutzbeauftragter (DSB)" },
      { type: "p", text: "Für die Tätigkeit ist keine DSB-Bestellung vorgeschrieben; die Bewertung ist dokumentiert und wird nach Volumen und Art der Verarbeitungen aktualisiert. Anfragen zum Datenschutz an den Verantwortlichen (Abschnitt 1)." },
      { type: "h2", text: "3. Kategorien verarbeiteter Daten" },
      { type: "p", text: "Je nach Interaktion kann der Verantwortliche folgende Datenkategorien verarbeiten:" },
      {
        type: "ul",
        items: [
          "Identitäts- und Kontaktdaten: Name, Nachname, E-Mail, Telefonnummer.",
          "Servicedaten (Erbschaftsakte): C.F., persönliche und vermögensbezogene Daten von Erben und Verstorbenem, Immobilien, Konten und Finanzbeziehungen, Verwandtschaftsgrade.",
          "Dokumente: Ausweis, Sterbeurkunde/-akt, Auszüge, Bescheinigungen und weitere für die Akte nötige Unterlagen.",
          "Zahlungsdaten: direkt durch Zahlungsanbieter (Stripe); der Verantwortliche speichert keine vollständigen Kartendaten.",
          "Technische und Navigationsdaten: IP-Adresse, Gerätekennungen, Logs, Cookies und ähnliche Technologien (Abschnitt 11 und Cookie-Richtlinie).",
        ],
      },
      { type: "p", text: "Manche Daten betreffen andere Personen (z. B. weitere Erben oder Verstorbenen): der Übermittler garantiert Berechtigung und informiert Betroffene über diese Erklärung (Art. 14 DSGVO)." },
      { type: "h2", text: "4. Zwecke und Rechtsgrundlagen" },
      {
        type: "table",
        headers: ["Zweck", "Rechtsgrundlage (DSGVO)"],
        rows: [
          ["Bearbeitung von Kostenvoranschlags-/Kontaktanfragen und vorvertragliche Maßnahmen", "Art. 6 Abs. 1 lit. b (vorvertragliche Maßnahmen)"],
          ["Erbringung der professionellen Dienstleistung (Erstellung und elektronische Übermittlung der Erbschaftserklärung, Umschreibungen)", "Art. 6 Abs. 1 lit. b (Vertrag)"],
          ["Steuerliche, buchhalterische und Aufbewahrungspflichten (Rechnung, Mandat)", "Art. 6 Abs. 1 lit. c (Rechtspflicht)"],
          ["Zahlungsabwicklung", "Art. 6 Abs. 1 lit. b und c"],
          ["Sicherheit der Website, Missbrauchs-/Betrugsprävention, Systemintegrität", "Art. 6 Abs. 1 lit. f (berechtigtes Interesse)"],
          ["Direktmarketing / Newsletter (falls aktiviert)", "Art. 6 Abs. 1 lit. a (Einwilligung)"],
          ["Cookies und nicht technische/Profiling-Technologien", "Art. 6 Abs. 1 lit. a (Einwilligung)"],
        ],
      },
      { type: "p", text: "In der Regel keine besonderen Kategorien nach Art. 9 DSGVO. Übermittelt der Kunde freiwillig zusätzliche Daten (z. B. Gesundheitsangaben in Dokumenten), Verarbeitung im Rahmen von Art. 9 Abs. 2 mit Empfehlung zur Datenminimierung." },
      { type: "h2", text: "5. Art der Bereitstellung" },
      { type: "p", text: "Daten für vertragliche, steuerliche und rechtliche Zwecke sind erforderlich — ohne sie keine Leistung. Marketing freiwillig; Ablehnung schadet dem Zugang nicht." },
      { type: "h2", text: "6. Verarbeitungsweise und Sicherheit" },
      { type: "p", text: "Verarbeitung mit IT-Mitteln und angemessenen technischen und organisatorischen Maßnahmen (Art. 32 DSGVO): Verschlüsselung in Transit und ruhend, Zugriffskontrolle, Row Level Security, Minimierung, Audit-Log. Zugang nur für Verantwortlichen und Beauftragte." },
      { type: "h2", text: "7. Empfänger und Auftragsverarbeiter" },
      { type: "p", text: "Zur Leistungserbringung nutzt der Verantwortliche Anbieter als Auftragsverarbeiter (Art. 28 DSGVO) mit DPA. Hauptkategorien und Anbieter:" },
      {
        type: "table",
        headers: ["Anbieter", "Rolle / Dienst", "Datenstandort"],
        rows: [
          ["Supabase", "Datenbank, Authentifizierung, Dokumentenspeicher", "EU"],
          ["Vercel", "Hosting und Bereitstellung der Anwendung", "EU (Funktionen) / ggf. außerhalb EU"],
          ["Stripe", "Zahlungsabwicklung", "EU/USA (SCC)"],
          ["Resend", "Transaktions-E-Mails", "EU/USA (SCC)"],
          ["Google Workspace", "Professionelle E-Mail des Studios", "EU/USA (SCC / DPF)"],
          ["OpenAI", "Unterstützte Extraktion von Aktdaten (interne Hilfe für den Fachmann)", "EU/USA (SCC / DPF)"],
          ["Meta Platforms (WhatsApp Cloud API)", "Messaging (falls aktiviert)", "EU/USA (SCC)"],
          ["Google (Analytics/Ads)", "Statistik und Werbung (nur nach Einwilligung)", "EU/USA (SCC)"],
          ["Cloudflare (Turnstile)", "Anti-Missbrauch-Schutz für Formulare (falls aktiviert)", "EU/USA (SCC)"],
        ],
      },
      { type: "p", text: "Daten können auch an öffentliche Stellen (z. B. Agenzia delle Entrate, Kataster) zur Leistungserbringung, an Vertrauenspersonen (Steuerberater/Notar) und an Behörden bei gesetzlicher Pflicht übermittelt werden. Keine Weitergabe zu eigenen Zwecken Dritter." },
      { type: "h2", text: "8. Übermittlung außerhalb der EU" },
      { type: "p", text: "Der Verantwortliche bevorzugt Anbieter mit Daten in der EU. Bei Verarbeitung außerhalb der EU: angemessene Garantien gemäß Art. 44 ff. DSGVO, insbesondere Standardvertragsklauseln (SCC) und/oder Angemessenheitsbeschlüsse (z. B. EU-US Data Privacy Framework)." },
      { type: "h2", text: "9. Aufbewahrungsdauer" },
      {
        type: "ul",
        items: [
          "Steuer- und Buchhaltungsunterlagen (Rechnungen, Belege, Mandat, Erklärung): gesetzliche Frist, mindestens 10 Jahre (Art. 2220 c.c. und Steuerpflichten).",
          "Vom Kunden hochgeladene sensible Eingangsdokumente (z. B. Personalausweis): nur für die Bearbeitung, danach Löschung aus der Cloud (Minimierung).",
          "Abschlussdokumente (AdE-Belege, aktualisierte Auszüge, Rechnung): im Persönlichen Bereich verfügbar; Archiv sicher aufbewahrt.",
          "Kontaktdaten für nicht konvertierte Kostenvoranschläge: Löschung oder Anonymisierung innerhalb 12 Monaten nach letztem Kontakt.",
          "Marketingdaten: bis Widerruf der Einwilligung.",
          "Technische/Log-Daten und Cookies: gemäß Cookie-Richtlinie.",
        ],
      },
      { type: "h2", text: "10. Rechte der betroffenen Person" },
      { type: "p", text: "Sie können jederzeit Rechte nach Art. 15–22 DSGVO ausüben: Auskunft, Berichtigung, Löschung (im Rahmen gesetzlicher Aufbewahrung), Einschränkung, Übertragbarkeit, Widerspruch, Widerruf der Einwilligung." },
      { type: "p", text: "Anfragen an die Kontakte in Abschnitt 1. Antwort ohne unangemessene Verzögerung, spätestens innerhalb eines Monats. Beschwerderecht beim Garante (www.garanteprivacy.it)." },
      { type: "h2", text: "11. Cookies und Tracking" },
      { type: "p", text: "Technische Cookies und, mit Einwilligung, Statistik-Cookies (Google Analytics 4 mit Consent Mode: keine Mess-Cookies ohne Einwilligung). Details in der Cookie-Richtlinie; Widerruf jederzeit über „Cookie-Einstellungen“ im Footer." },
      { type: "h2", text: "12. Automatisierte Entscheidungen und KI" },
      { type: "p", text: "Keine automatisierte Entscheidung mit rechtlicher Wirkung nach Art. 22 DSGVO. KI nur als interne Unterstützung: Aktdokumente können per OpenAI-API (Auftragsverarbeiter, Abschnitt 7) zur Datenermittlung verarbeitet werden." },
      {
        type: "ul",
        items: [
          "Per API übermittelte Daten werden von OpenAI nicht zum Modelltraining genutzt.",
          "Jeder extrahierte Wert wird vom Fachmann geprüft und validiert — Entscheidung immer menschlich.",
          "Etwaige Drittlandübermittlung mit Garantien aus Abschnitt 8.",
        ],
      },
      { type: "h2", text: "13. Minderjährige" },
      { type: "p", text: "Leistungen richten sich an Volljährige. Keine wissentliche Erhebung von Minderjährigendaten ohne elterliche Einwilligung." },
      { type: "h2", text: "14. Änderungen dieser Erklärung" },
      { type: "p", text: "Der Verantwortliche kann diese Erklärung aktualisieren. Aktuelle Fassung mit Datum auf dieser Seite; bei wesentlichen Änderungen entsprechende Hinweise." },
    ],
  },
  termini: {
    slug: "termini",
    title: "Verkaufsbedingungen",
    eyebrow: "Rechtsdokument",
    intro: "AGB für Fernabsatz professioneller Dienstleistungen an Verbraucher (D.Lgs. 206/2005, Verbraucherschutzgesetz).",
    updatedAt: "Letzte Aktualisierung: 14. Juli 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "1. Angaben zum Fachmann (Art. 49 Verbraucherschutzgesetz)" },
      {
        type: "ul",
        items: [
          "Fachmann: {{ragione_sociale}} ({{forma_giuridica}})",
          "Betriebsadresse: {{indirizzo}}",
          "P.IVA: {{piva}} - C.F.: {{cf}}",
          "Kammereintragung: {{albo}}",
          "PEC: {{pec}} - E-Mail: {{email}} - Telefon: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Gegenstand und Anwendungsbereich" },
      { type: "p", text: "Diese Bedingungen regeln den Fernabsatz professioneller Leistungen über die Website: Unterstützung bei Erstellung und elektronischer Übermittlung der Erbschaftserklärung und verbundener Pflichten (z. B. Katasterumschreibungen) je nach Paket." },
      { type: "p", text: "Elektronische Übermittlung an Agenzia delle Entrate durch den Fachmann als Entratel-Vermittler nach Mandat und unterzeichneter Erklärung. Vertrag schließt aus der Ferne elektronisch." },
      { type: "h2", text: "3. Pakete, Preise und Ausnahmen" },
      { type: "p", text: "Pakete und Honorarpreise auf der Preisseite. Preis = ausschließlich professionelles Honorar." },
      { type: "callout", tone: "warning", title: "Honorar und Steuern sind verschiedene Dinge", text: "Staatliche Steuern und Abgaben (Erbschaftsteuer in Selbstanzeige, Hypotheken-, Kataster-, Stempelsteuern usw.) sind NICHT im Servicepreis: fallbezogen berechnet, vor Einreichung mitgeteilt, vom Erben gezahlt. Kein Aufschlag." },
      {
        type: "ul",
        items: [
          "Nicht im Paket, sofern nicht anders vereinbart: nicht genannte Leistungen (Streit, Notariat, komplexe Steuerberatung, nicht lineare Fälle). Zusatzleistungen separat kalkuliert.",
          "Individueller Kostenvoranschlag (komplexe Fälle): bei Übersteigen standardmäßiger Pakete (viele Immobilien, Agrarflächen, Gesellschaftsanteile, Testamentsfälle, Auslandserben, Dokumentenbeschaffung) individueller Preis vor Kauf.",
          "Nach Fragebogen vorgeschlagenes Paket ist orientierend: nach Dokumentenprüfung ggf. Änderung und Ausgleich (Art. 5).",
          "Vorprüfung Nicht-Pflicht: bei Hinweis auf fehlende Pflicht informieren wir — endgültige Bewertung am konkreten Fall.",
        ],
      },
      { type: "h2", text: "4. Vertragsschluss" },
      { type: "p", text: "Kostenvoranschlagsanfrage unverbindlich. Vertrag mit Paketzahlung und ausdrücklicher Annahme dieser Bedingungen beim Checkout." },
      { type: "h2", text: "5. Zahlung und Paketänderung" },
      { type: "p", text: "Honorarvorauszahlung über Stripe. Rechnung nach geltendem Recht. Staatssteuern separat vom Erben." },
      { type: "p", text: "Paketänderung und Ausgleich: bei Vereinbarung Differenzausgleich — höheres Paket: Nachzahlung; niedrigeres: Erstattung der Differenz. Bestätigung auf dauerhaftem Medium. Staatssteuern ausgeschlossen." },
      { type: "h2", text: "6. Pflichten und Haftung des Kunden" },
      {
        type: "ul",
        items: [
          "Wahrheitsgemäße, vollständige und rechtzeitige Daten und Dokumente — Verantwortung des Kunden.",
          "Keine Haftung für Verzögerungen, Fehler oder Bußgelder durch falsche, unvollständige oder verspätete Kundenangaben oder Drittzeiten (Agenzia, Kataster, Banken).",
          "Mandat erteilen und Erklärung fristgerecht unterzeichnen.",
        ],
      },
      { type: "h2", text: "7. Ausführungsfristen" },
      { type: "p", text: "Lieferzeiten ab vollständiger, korrekter, vom Fachmann validierter Dokumentation (nicht ab Zahlung). Bei Unvollständigkeit Frist suspendiert bis letztes fehlendes Dokument." },
      { type: "h2", text: "8. Widerrufsrecht (Art. 52–59 Verbraucherschutzgesetz)" },
      {
        type: "ul",
        items: [
          "Verbraucher kann innerhalb 14 Tagen ohne Angabe von Gründen widerrufen; bei Dienstleistungen ab Vertragsschluss.",
          "Widerruf per Musterformular oder ausdrücklicher Erklärung an Abschnitt 1. Bestätigung unverzüglich.",
          "Sofortiger Beginn: ausdrücklicher Wunsch während der Widerrufsfrist — bei vollständiger Leistung innerhalb 14 Tagen entfällt Widerrufsrecht (Art. 59 Abs. 1 lit. a).",
          "Widerruf nach Beginn vor Abschluss: anteilige Vergütung für bereits erbrachte Leistung (Art. 57 Abs. 3).",
          "Erstattung mit gleicher Zahlungsmethode, unverzüglich, spätestens innerhalb 14 Tagen.",
        ],
      },
      { type: "callout", tone: "info", text: "Widerruf einfach erklärt auf /recesso. Dieser formelle Text ist maßgeblich." },
      { type: "h2", text: "9. Handelsgarantie „Zufrieden oder Geld zurück“" },
      { type: "p", text: "Freiwillige Erstattungsgarantie gemäß Garantieseite — zusätzlich, ohne Einschränkung gesetzlicher Rechte." },
      { type: "h2", text: "10. Haftungsbeschränkungen" },
      { type: "p", text: "Sorgfalt eines ordentlichen Fachmanns (Schuldnerqualifikation). Haftung außer bei Vorsatz/grober Fahrlässigkeit und gesetzlichen Grenzen am Honorar orientiert. Keine Haftung für Dritte, höhere Gewalt, externe Anbieter." },
      { type: "h2", text: "11. Eigentum an Dokumenten und Zugang" },
      { type: "p", text: "Abschlussdokumente (Belege, aktualisierte Auszüge, Rechnung) im Persönlichen Bereich. Aufbewahrung gemäß Datenschutzerklärung." },
      { type: "h2", text: "12. Verarbeitung personenbezogener Daten" },
      { type: "p", text: "Beschrieben in der Datenschutzerklärung auf der Website — integraler Bestandteil des Vertragsverhältnisses." },
      { type: "h2", text: "13. Änderungen" },
      { type: "p", text: "Der Fachmann kann diese Bedingungen ändern; es gilt die beim Kauf akzeptierte Fassung. Aktuelle Fassung auf der Website." },
      { type: "h2", text: "14. Anwendbares Recht, Gerichtsstand und Streitbeilegung" },
      { type: "p", text: "Italienisches Recht. Für Verbraucher zwingender Gerichtsstand am Wohnsitz. Beschwerden an Abschnitt 1. ODR-Plattform: https://ec.europa.eu/consumers/odr und zuständige Mediations-/ADR-Stellen." },
    ],
  },
  cookie: {
    slug: "cookie",
    title: "Cookie-Richtlinie",
    eyebrow: "Rechtsdokument",
    intro: "Cookies und ähnliche Technologien sowie Verwaltung Ihrer Einwilligungen.",
    updatedAt: "Letzte Aktualisierung: 14. Juli 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Was Cookies sind" },
      { type: "p", text: "Kleine Textdateien auf Ihrem Gerät für Funktion, Präferenzen oder — mit Einwilligung — Statistik. Dazu local storage, Pixel usw." },
      { type: "h2", text: "Von uns genutzte Kategorien" },
      {
        type: "table",
        headers: ["Kategorie", "Zweck", "Grundlage / Einwilligung"],
        rows: [
          ["Technisch / erforderlich", "Websitebetrieb, Sicherheit, Sitzung im Persönlichen Bereich, Cookie-Einstellungen.", "Immer aktiv (keine Einwilligung nötig)"],
          ["Analytisch (Google Analytics 4)", "Aggregierte Nutzungsstatistik zur Verbesserung. Mit Consent Mode keine Mess-Cookies ohne Einwilligung.", "Nur nach Einwilligung"],
          ["Marketing", "Kampagnenmessung und Attribution (z. B. Google Ads). Derzeit nicht aktiv ohne Banner-Einwilligung.", "Nur nach Einwilligung"],
        ],
      },
      { type: "h2", text: "Einwilligung verwalten" },
      { type: "p", text: "Banner beim ersten Besuch: gleichwertige Annahme/Ablehnung nicht erforderlicher Cookies. Jederzeit über Footer-Link ändern oder widerrufen." },
      { type: "h2", text: "Deaktivierung im Browser" },
      { type: "p", text: "Cookies auch in Browser-Einstellungen verwalten oder löschen. Deaktivierung technischer Cookies kann Funktionen einschränken (z. B. Persönlicher Bereich)." },
      { type: "h2", text: "Verantwortlicher und Kontakte" },
      { type: "p", text: "Verantwortlicher: {{ragione_sociale}}, {{indirizzo}}. E-Mail: {{email}} - PEC: {{pec}}. Details in der Datenschutzerklärung." },
    ],
  },
  garanzia: {
    slug: "garanzia",
    title: "Unsere Garantie",
    eyebrow: "Ihr Schutz",
    intro: "Versprechen „Zufrieden oder Geld zurück“: zusätzlicher Schutz neben Ihren gesetzlichen Rechten.",
    updatedAt: "Vorläufige Fassung — Detailbedingungen noch festzulegen",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Das Versprechen" },
      { type: "p", text: "Damit Sie von Anfang bis Ende ruhig sind: neben gesetzlichem Schutz freiwillige „Zufrieden oder Geld zurück“-Garantie — bei Problemen sprechen wir und finden eine Lösung bis zur Erstattung." },
      { type: "h2", text: "So funktioniert es" },
      {
        type: "ol",
        items: [
          "Problem melden per E-Mail oder im Persönlichen Bereich.",
          "Gemeinsame transparente Prüfung.",
          "Bei abgedeckten Fällen Erstattung mit gleicher Zahlungsmethode in den angegebenen Fristen. (Details noch festzulegen.)",
        ],
      },
      { type: "callout", tone: "info", title: "Garantie und Widerruf sind verschieden", text: "Widerruf: gesetzliches Recht in 14 Tagen (Seite Widerruf). Garantie: freiwillige Zusatzleistung ohne Einschränkung Verbraucherrechte." },
      { type: "h2", text: "Nicht abgedeckt" },
      {
        type: "ul",
        items: [
          "Staatliche Steuern und Abgaben (nicht unser Honorar, kein Aufschlag).",
          "Verzögerungen durch falsche, unvollständige oder verspätete Kundendokumente.",
          "Zeiten und Entscheidungen Dritter (Agenzia delle Entrate, Kataster, Banken).",
        ],
      },
    ],
    cta: { label: "Kostenlosen Kostenvoranschlag berechnen", href: "/preventivo" },
  },
};
