import type { LegalDoc, LegalSlug } from "./legal";

/*
  Spanish courtesy translation of legal documents.
  Italian version is binding — see notice on each document.
  {{tokens}} unchanged (replaced at render-time).
*/

const LANG_NOTE =
  "La versión italiana de este documento es jurídicamente vinculante: cualquier traducción es solo de cortesía y, en caso de conflicto, prevalece el texto italiano.";

const LANG_NOTICE = {
  tone: "info" as const,
  text: LANG_NOTE,
};

export const legalDocsEs: Record<LegalSlug, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "Política de privacidad",
    eyebrow: "Documento legal",
    intro: "Cómo tratamos tus datos personales cuando consultas el sitio, solicitas un presupuesto, compras un servicio o usas tu área personal, conforme al RGPD (Regl. UE 2016/679).",
    updatedAt: "Última actualización: 14 de julio de 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "p", text: "De conformidad con los artículos 13 y 14 del Reglamento (UE) 2016/679 («RGPD») y el D.Lgs. 196/2003 («Código de Privacidad») modificado por el D.Lgs. 101/2018, el Estudio facilita la siguiente información sobre el tratamiento de datos personales." },
      { type: "h2", text: "1. Responsable del tratamiento" },
      {
        type: "ul",
        items: [
          "Responsable: {{ragione_sociale}} ({{forma_giuridica}})",
          "Sede operativa: {{indirizzo}}",
          "P.IVA: {{piva}} - Código Fiscal: {{cf}}",
          "Inscripción en el Colegio: {{albo}}",
          "PEC: {{pec}} - Correo: {{email}} - Teléfono: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Delegado de protección de datos (DPO)" },
      { type: "p", text: "La designación de un DPO no resulta obligatoria para la actividad ejercida; la evaluación está documentada por el Responsable y se actualiza según volúmenes y naturaleza de los tratamientos. Para cualquier solicitud sobre datos personales puedes contactar al Responsable en los datos de la sección 1." },
      { type: "h2", text: "3. Categorías de datos tratados" },
      { type: "p", text: "Según la interacción, el Responsable puede tratar las siguientes categorías de datos:" },
      {
        type: "ul",
        items: [
          "Datos identificativos y de contacto: nombre, apellidos, correo, número de teléfono.",
          "Datos relativos al servicio (expediente de sucesión): código fiscal, datos personales y patrimoniales del heredero y del fallecido, datos sobre inmuebles, cuentas corrientes y relaciones financieras, grados de parentesco.",
          "Documentos: documento de identidad, certificado/acta de defunción, notas, certificaciones y demás documentos necesarios para el expediente.",
          "Datos de pago: gestionados directamente por el proveedor de pago (Stripe); el Responsable no memoriza los datos completos de la tarjeta.",
          "Datos técnicos y de navegación: dirección IP, identificadores de dispositivos, registros, cookies y tecnologías similares (ver sección 11 y Política de cookies).",
        ],
      },
      { type: "p", text: "Algunos datos pueden referirse a personas distintas del usuario que los comunica (p. ej. otros herederos o el fallecido): quien los facilita garantiza estar legitimado para comunicarlos y se compromete a informar a los interesados de la presente política (art. 14 RGPD)." },
      { type: "h2", text: "4. Finalidades del tratamiento y bases jurídicas" },
      {
        type: "table",
        headers: ["Finalidad", "Base jurídica (RGPD)"],
        rows: [
          ["Atención a solicitudes de presupuesto/contacto y actividades precontractuales", "Art. 6.1.b (medidas precontractuales)"],
          ["Ejecución del servicio profesional (preparación y envío telemático de la declaración de sucesión, voluture)", "Art. 6.1.b (contrato)"],
          ["Cumplimientos fiscales, contables y de conservación (facturación, mandato profesional)", "Art. 6.1.c (obligación legal)"],
          ["Gestión de pagos", "Art. 6.1.b y 6.1.c"],
          ["Seguridad del sitio, prevención de abusos/fraudes, integridad de los sistemas", "Art. 6.1.f (interés legítimo)"],
          ["Marketing directo / newsletter (si se activa)", "Art. 6.1.a (consentimiento)"],
          ["Cookies y tecnologías no técnicas/de perfilado", "Art. 6.1.a (consentimiento)"],
        ],
      },
      { type: "p", text: "Por norma no está prevista la recogida de categorías particulares de datos ex art. 9 RGPD. Si el cliente transmite espontáneamente datos excedentes (p. ej. información sanitaria en un documento), el Responsable los trata en los límites del art. 9.2 y recomienda su minimización." },
      { type: "h2", text: "5. Naturaleza del suministro" },
      { type: "p", text: "El suministro de datos para finalidades contractuales, fiscales y legales es necesario: la falta de suministro impide la prestación del servicio. El suministro para finalidades de marketing es opcional y un eventual rechazo no perjudica el acceso al servicio." },
      { type: "h2", text: "6. Modalidades del tratamiento y seguridad" },
      { type: "p", text: "Los datos se tratan con herramientas informáticas y medidas técnicas y organizativas adecuadas (art. 32 RGPD): cifrado en tránsito y en reposo, control de accesos, segmentación mediante Row Level Security, principio de minimización, registro de accesos (audit log). El acceso está reservado al Responsable y a los encargados autorizados." },
      { type: "h2", text: "7. Destinatarios y encargados del tratamiento" },
      { type: "p", text: "Para prestar el servicio, el Responsable se apoya en proveedores que tratan los datos como encargados del tratamiento (art. 28 RGPD), vinculados por acuerdo apropiado (DPA). Las principales categorías y proveedores son:" },
      {
        type: "table",
        headers: ["Proveedor", "Rol / servicio", "Ubicación de datos"],
        rows: [
          ["Supabase", "Base de datos, autenticación, almacenamiento de documentos", "UE"],
          ["Vercel", "Alojamiento y distribución de la aplicación", "UE (funciones) / posible extra-UE"],
          ["Stripe", "Procesamiento de pagos", "UE/EE.UU. (SCC)"],
          ["Resend", "Envío de correos transaccionales", "UE/EE.UU. (SCC)"],
          ["Google Workspace", "Correo profesional del Estudio", "UE/EE.UU. (SCC / DPF)"],
          ["OpenAI", "Extracción asistida de datos de los documentos del expediente (apoyo interno al profesional)", "UE/EE.UU. (SCC / DPF)"],
          ["Meta Platforms (WhatsApp Cloud API)", "Mensajería (si se activa)", "UE/EE.UU. (SCC)"],
          ["Google (Analytics/Ads)", "Estadísticas y publicidad (solo con consentimiento previo)", "UE/EE.UU. (SCC)"],
          ["Cloudflare (Turnstile)", "Protección antiabuso de formularios (si se activa)", "UE/EE.UU. (SCC)"],
        ],
      },
      { type: "p", text: "Los datos pueden comunicarse además a organismos públicos (p. ej. Agenzia delle Entrate, Catasto) para el cumplimiento del servicio, a profesionales de confianza (p. ej. asesor fiscal/notario) cuando sea necesario, y a autoridades judiciales/fuerzas del orden si la ley lo exige. Los datos NO se difunden ni ceden a terceros para sus propias finalidades." },
      { type: "h2", text: "8. Transferencia de datos fuera de la UE" },
      { type: "p", text: "El Responsable privilegia proveedores con datos en la Unión Europea. Cuando algunos proveedores tratan datos fuera de la UE (p. ej. en EE.UU.), la transferencia se realiza sobre la base de garantías adecuadas según los art. 44 y ss. RGPD, en particular las Cláusulas Contractuales Tipo (SCC) de la Comisión Europea y/o decisiones de adecuación (p. ej. EU-US Data Privacy Framework, cuando aplique)." },
      { type: "h2", text: "9. Periodo de conservación" },
      {
        type: "ul",
        items: [
          "Documentos fiscales y contables (facturas, recibos, mandato, declaración): conservados durante el plazo legal, al menos 10 años (art. 2220 c.c. y obligaciones fiscales).",
          "Documentos sensibles de entrada subidos por el cliente (p. ej. documento de identidad): conservados el tiempo necesario para la tramitación y luego eliminados de la nube (minimización).",
          "Documentos finales (recibos AdE, notas actualizadas, factura): disponibles en el área personal del cliente para consulta; el archivo completo se conserva de forma segura.",
          "Datos de contacto para presupuestos no convertidos: eliminados o anonimizados en 12 meses desde el último contacto.",
          "Datos de marketing: hasta revocación del consentimiento.",
          "Datos técnicos/registros y cookies: según las duraciones indicadas en la Política de cookies.",
        ],
      },
      { type: "h2", text: "10. Derechos del interesado" },
      { type: "p", text: "Puedes ejercer en cualquier momento los derechos previstos en los art. 15-22 RGPD: acceso, rectificación, supresión («derecho al olvido», dentro de los límites de las obligaciones legales de conservación), limitación, portabilidad, oposición al tratamiento basado en interés legítimo, revocación del consentimiento en cualquier momento (sin perjudicar la licitud del tratamiento anterior)." },
      { type: "p", text: "Las solicitudes deben enviarse a los datos de la sección 1. El Responsable responde sin demora indebida y en todo caso en un mes. Tienes además derecho a presentar reclamación ante el Garante per la protezione dei dati personali (www.garanteprivacy.it)." },
      { type: "h2", text: "11. Cookies y tecnologías de seguimiento" },
      { type: "p", text: "El sitio utiliza cookies técnicas y, con consentimiento previo, cookies de estadística (Google Analytics 4 con Consent Mode: ninguna cookie de medición se instala sin consentimiento). El detalle de categorías, finalidades y duraciones figura en la Política de cookies dedicada, accesible desde el banner y el pie de página. El consentimiento es revocable en cualquier momento desde el enlace «Preferencias de cookies» en el pie de página." },
      { type: "h2", text: "12. Proceso decisional automatizado e inteligencia artificial" },
      { type: "p", text: "No se realiza ningún proceso decisional automatizado que produzca efectos jurídicos sobre el interesado según el art. 22 RGPD. El Estudio utiliza herramientas de inteligencia artificial exclusivamente como apoyo interno a la actividad del profesional: en particular, los documentos subidos para el expediente pueden procesarse mediante el servicio API de OpenAI (encargado del tratamiento, ver sección 7) para extraer los datos necesarios a la preparación de la declaración (p. ej. datos personales, catastrales)." },
      {
        type: "ul",
        items: [
          "Los datos enviados vía API no son utilizados por OpenAI para entrenar sus propios modelos.",
          "Cada dato extraído es verificado y validado por el profesional antes de su uso: la decisión final siempre recae en una persona.",
          "La transferencia extra-UE eventualmente vinculada se realiza con las garantías de la sección 8.",
        ],
      },
      { type: "h2", text: "13. Menores" },
      { type: "p", text: "Los servicios se dirigen a personas mayores de edad. El Responsable no recoge conscientemente datos de menores sin el consentimiento de quien ejerce la responsabilidad parental." },
      { type: "h2", text: "14. Modificaciones de la política" },
      { type: "p", text: "El Responsable puede actualizar la presente política. La versión vigente se publica siempre en esta página con la fecha de última actualización; en caso de modificaciones sustanciales se dará la debida visibilidad." },
    ],
  },
  termini: {
    slug: "termini",
    title: "Condiciones de venta",
    eyebrow: "Documento legal",
    intro: "Los términos y condiciones que regulan la venta a distancia de nuestros servicios profesionales a consumidores (D.Lgs. 206/2005, Código del Consumo).",
    updatedAt: "Última actualización: 14 de julio de 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "1. Información sobre el profesional (art. 49 Cód. Consumo)" },
      {
        type: "ul",
        items: [
          "Profesional: {{ragione_sociale}} ({{forma_giuridica}})",
          "Sede operativa: {{indirizzo}}",
          "P.IVA: {{piva}} - Código Fiscal: {{cf}}",
          "Inscripción en el Colegio: {{albo}}",
          "PEC: {{pec}} - Correo: {{email}} - Teléfono: {{telefono}}",
        ],
      },
      { type: "h2", text: "2. Objeto y ámbito de aplicación" },
      { type: "p", text: "Las presentes Condiciones regulan la venta a distancia de los servicios profesionales ofrecidos a través del sitio, consistentes en la asistencia para la preparación y transmisión telemática de la declaración de sucesión y cumplimientos conexos (p. ej. voluture catastrales), según el paquete adquirido." },
      { type: "p", text: "El envío telemático a la Agenzia delle Entrate lo realiza el profesional como intermediario habilitado ENTRATEL, previo otorgamiento de mandato/encargo apropiado y recepción de la declaración firmada por el cliente. El contrato se celebra a distancia, por vía electrónica." },
      { type: "h2", text: "3. Paquetes, precios y exclusiones" },
      { type: "p", text: "Los paquetes y los precios correspondientes (honorarios) figuran en la página Tarifas. El precio indicado se refiere exclusivamente a los honorarios profesionales." },
      { type: "callout", tone: "warning", title: "Honorarios e impuestos son cosas distintas", text: "Los impuestos y tributos debidos al Estado (p. ej. impuesto de sucesión en autoliquidación, impuestos hipotecario, catastral, de timbre, tributos especiales) NO están incluidos en el precio del servicio: se calculan según la situación concreta, se comunican al cliente antes del envío y los paga el heredero. El profesional no aplica ningún recargo sobre esos importes." },
      {
        type: "ul",
        items: [
          "Quedan excluidos del paquete, salvo acuerdo distinto, servicios no indicados expresamente (p. ej. contencioso, actos notariales, asesorías fiscales complejas, casos no lineales). Las actividades adicionales se presupuestan aparte.",
          "Presupuesto personalizado (casos complejos): para expedientes que por naturaleza o complejidad exceden los paquetes estándar (p. ej. pluralidad de inmuebles, terrenos/parcelas agrícolas, participaciones societarias, sucesiones testamentarias, herederos en el extranjero, recuperación documental), el precio se determina mediante presupuesto individual comunicado antes de la compra.",
          "El paquete propuesto tras el cuestionario en línea es orientativo: tras la verificación de la documentación puede aplicarse el procedimiento de modificación y regularización (art. 5).",
          "Verificación preliminar de no obligación: cuando de los datos facilitados resulte que la declaración no es debida por ley, el profesional lo indica al cliente; la valoración definitiva requiere el examen del caso concreto.",
        ],
      },
      { type: "h2", text: "4. Conclusión del contrato" },
      { type: "p", text: "La solicitud de presupuesto no es vinculante. El contrato se perfecciona con el pago del paquete y la aceptación explícita de las presentes Condiciones en el checkout. Antes de la compra el cliente toma conocimiento de las características del servicio, del precio total, de las presentes Condiciones y de la política de privacidad." },
      { type: "h2", text: "5. Pago y modificación del paquete" },
      { type: "p", text: "El pago de los honorarios se realiza por anticipado mediante el proveedor de pago (Stripe). La factura se emite según las obligaciones vigentes. Los impuestos estatales se gestionan por separado y los paga el heredero según las modalidades comunicadas." },
      { type: "p", text: "Modificación del paquete y regularización: si, de acuerdo con el cliente, se modifica el paquete, se procede a la regularización de la diferencia. En caso de paso a un paquete superior, el cliente integra la diferencia mediante enlace de pago; en caso de paquete inferior, la diferencia ya abonada se reembolsa por el mismo medio, sin demora. La modificación se confirma en soporte durable. Los impuestos estatales quedan en todo caso excluidos de la regularización." },
      { type: "h2", text: "6. Obligaciones y responsabilidad del cliente" },
      {
        type: "ul",
        items: [
          "El cliente facilita datos y documentos veraces, completos y oportunos y es responsable de su corrección.",
          "El profesional no responde de retrasos, errores o sanciones derivados de informaciones o documentos erróneos, incompletos o facilitados tarde por el cliente, ni de los plazos de tramitación de organismos terceros (Agenzia delle Entrate, Catasto, bancos).",
          "El cliente se compromete a otorgar el mandato y firmar la declaración en los plazos requeridos.",
        ],
      },
      { type: "h2", text: "7. Plazos de ejecución" },
      { type: "p", text: "Los plazos de entrega indicados en el sitio son estimaciones que corren desde el momento en que el cliente ha facilitado toda la documentación necesaria, completa, correcta y validada por el profesional (y no desde la fecha de pago), y no comprenden los plazos de organismos terceros. Mientras la documentación esté incompleta o pendiente de integración, el plazo queda suspendido y reanuda con la recepción/validación del último documento faltante." },
      { type: "h2", text: "8. Derecho de desistimiento (art. 52-59 Cód. Consumo)" },
      {
        type: "ul",
        items: [
          "El consumidor tiene derecho a desistir del contrato en 14 días sin necesidad de motivación; para servicios, el plazo corre desde la conclusión del contrato.",
          "Para ejercer el desistimiento el cliente puede usar el modelo tipo o cualquier declaración explícita enviada a los datos de la sección 1. El profesional confirma sin demora la recepción.",
          "Inicio inmediato: si el cliente pide expresamente que la tramitación comience durante el periodo de desistimiento, presta consentimiento expreso al inicio inmediato y reconoce que pierde el derecho de desistimiento una vez prestado integralmente el servicio (art. 59, párr. 1, letra a).",
          "Desistimiento tras el inicio pero antes de la finalización: el cliente abona un importe proporcional al servicio ya prestado hasta la comunicación del desistimiento (art. 57, párr. 3).",
          "El reembolso eventual se efectúa por el mismo medio de pago, sin demora y en todo caso en 14 días.",
        ],
      },
      { type: "callout", tone: "info", text: "Explicamos el desistimiento en términos sencillos en la página dedicada /recesso. Este texto formal es el vinculante." },
      { type: "h2", text: "9. Garantía comercial «Satisfechos o reembolsados»" },
      { type: "p", text: "El profesional puede ofrecer, además y voluntariamente, una garantía de reembolso en las condiciones indicadas en la página Garantía. Dicha garantía es adicional y no limita los derechos legales del consumidor." },
      { type: "h2", text: "10. Limitaciones de responsabilidad" },
      { type: "p", text: "El profesional ejecuta el encargo con diligencia profesional (obligación de medios). Salvo dolo o culpa grave, y dentro de los límites legales, la responsabilidad es proporcional al importe de los honorarios abonados por el expediente. El profesional no responde de hechos imputables a terceros, fuerza mayor o mal funcionamiento de proveedores externos." },
      { type: "h2", text: "11. Propiedad de los documentos y acceso" },
      { type: "p", text: "Los documentos finales (recibos, notas actualizadas, factura) se ponen a disposición en el área personal del cliente para consulta y descarga, según los plazos indicados. La conservación se rige por la política de privacidad." },
      { type: "h2", text: "12. Tratamiento de datos personales" },
      { type: "p", text: "El tratamiento de datos se describe en la Política de Privacidad disponible en el sitio, que forma parte integrante de la relación." },
      { type: "h2", text: "13. Modificaciones" },
      { type: "p", text: "El profesional puede modificar las presentes Condiciones; al contrato se aplica la versión aceptada en el momento de la compra. La versión vigente se publica siempre en el sitio." },
      { type: "h2", text: "14. Ley aplicable, fuero y resolución de controversias" },
      { type: "p", text: "Al contrato se aplica la ley italiana. Para consumidores permanece el fuero imperativo del lugar de residencia/domicilio del consumidor. Reclamaciones a los datos de la sección 1. El consumidor puede acudir a la plataforma europea ODR (https://ec.europa.eu/consumers/odr) y a organismos de mediación/ADR competentes." },
    ],
  },
  cookie: {
    slug: "cookie",
    title: "Política de cookies",
    eyebrow: "Documento legal",
    intro: "Las cookies y tecnologías similares que utilizamos, y cómo gestionar tus consentimientos.",
    updatedAt: "Última actualización: 14 de julio de 2026",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "Qué son las cookies" },
      { type: "p", text: "Las cookies son pequeños archivos de texto que los sitios guardan en tu dispositivo para hacerlo funcionar, recordar tus preferencias o recoger estadísticas. Junto con las cookies usamos tecnologías similares (p. ej. almacenamiento local, píxeles)." },
      { type: "h2", text: "Categorías que utilizamos" },
      {
        type: "table",
        headers: ["Categoría", "Para qué sirven", "Base / consentimiento"],
        rows: [
          ["Técnicas / necesarias", "Funcionamiento del sitio, seguridad, sesión de acceso al área personal, memorización de las elecciones sobre cookies.", "Siempre activas (no requieren consentimiento)"],
          ["Analíticas (Google Analytics 4)", "Estadísticas agregadas sobre el uso del sitio para mejorarlo. Gracias al Consent Mode, ninguna cookie de medición se instala sin tu consentimiento.", "Solo con consentimiento previo"],
          ["Marketing", "Medición de campañas publicitarias y atribución (p. ej. Google Ads). Por ahora no activas: si se activan, requerirán consentimiento desde el banner.", "Solo con consentimiento previo"],
        ],
      },
      { type: "h2", text: "Cómo gestionas el consentimiento" },
      { type: "p", text: "En la primera visita un banner te permite aceptar o rechazar las cookies no necesarias, con igual visibilidad entre las opciones. Puedes modificar o revocar el consentimiento en cualquier momento desde el enlace «Preferencias de cookies» en el pie del sitio; la revocación no perjudica la licitud de los tratamientos anteriores." },
      { type: "h2", text: "Desactivación desde el navegador" },
      { type: "p", text: "También puedes gestionar o eliminar las cookies desde la configuración de tu navegador. Desactivar las cookies técnicas puede comprometer algunas funciones del sitio (p. ej. el acceso al área personal)." },
      { type: "h2", text: "Responsable y contactos" },
      { type: "p", text: "Responsable del tratamiento: {{ragione_sociale}}, {{indirizzo}}. Correo: {{email}} - PEC: {{pec}}. Para el detalle del tratamiento de datos personales ver la Política de privacidad." },
    ],
  },
  garanzia: {
    slug: "garanzia",
    title: "Nuestra garantía",
    eyebrow: "Tus garantías",
    intro: "La promesa Satisfechos o reembolsados: una protección extra que ofrecemos nosotros, además de tus derechos legales.",
    updatedAt: "Versión preliminar - condiciones de detalle por definir",
    notice: LANG_NOTICE,
    body: [
      { type: "h2", text: "La promesa" },
      { type: "p", text: "Queremos que estés tranquilo/a de principio a fin. Por eso, además de las garantías legales, ofrecemos voluntariamente una garantía «Satisfechos o reembolsados»: si algo no va como acordamos, lo hablamos y buscamos una solución, hasta el reembolso en los casos previstos." },
      { type: "h2", text: "Cómo funciona" },
      {
        type: "ol",
        items: [
          "Nos señalas el problema escribiéndonos o desde tu área personal.",
          "Verificamos juntos la situación, de forma transparente.",
          "Si entra en los casos cubiertos, procedemos al reembolso por el mismo método de pago, en los plazos indicados. (Casos, importes y plazos específicos: por definir.)",
        ],
      },
      { type: "callout", tone: "info", title: "Garantía y desistimiento son dos cosas distintas", text: "El desistimiento es tu derecho legal en los primeros 14 días (ver página Desistimiento). La garantía Satisfechos o reembolsados es una promesa comercial extra, voluntaria, que no limita en modo alguno tus derechos de consumidor." },
      { type: "h2", text: "Qué no cubre" },
      {
        type: "ul",
        items: [
          "Los impuestos y tributos debidos al Estado (no son nuestros honorarios y no tienen recargo).",
          "Retrasos o resultados derivados de documentos erróneos, incompletos o facilitados tarde por el cliente.",
          "Plazos y decisiones de organismos terceros (Agenzia delle Entrate, Catasto, bancos).",
        ],
      },
    ],
    cta: { label: "Calcula el presupuesto gratis", href: "/preventivo" },
  },
};
